/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { useEffect } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Dodge_ViperGTS_2015_Wheel_2Combined3DWheel_3DWheel_Front_L_Inst: THREE.Mesh
    Dodge_ViperGTS_2015_CallipersCombinedCalliperExotic4Callipe: THREE.Mesh
    Dodge_ViperGTS_2015_Wheel_2Combined3DWheel_3DWheel_Front_L_001: THREE.Mesh
    Dodge_ViperGTS_2015Engine_Geo_lodA: THREE.Mesh
    Dodge_ViperGTS_2015Grille2_Geo_lodA: THREE.Mesh
    Dodge_ViperGTS_2015Kit0_Badge_Geo_lodA: THREE.Mesh
    Dodge_ViperGTS_2015Kit0_Base_Geo_lodA: THREE.Mesh
    Dodge_ViperGTS_2015Kit0_Carbon1_Geo_lodA: THREE.Mesh
    Dodge_ViperGTS_2015Kit0_Coloured_Geo_lodA: THREE.Mesh
    Dodge_ViperGTS_2015Kit0_Grille1_Geo_lodA: THREE.Mesh
    Dodge_ViperGTS_2015Kit0_Interior_Geo_lodA: THREE.Mesh
    Dodge_ViperGTS_2015Kit0_InteriorTillingColourZone_Geo_lodA: THREE.Mesh
    Dodge_ViperGTS_2015Kit0_Paint_Geo_lodA: THREE.Mesh
    Dodge_ViperGTS_2015Kit0_SeatBelt_Geo_lodA: THREE.Mesh
    Dodge_ViperGTS_2015ManufacturerPlate_Geo_lodA: THREE.Mesh
    Dodge_ViperGTS_2015Window_Geo_lodA: THREE.Mesh
    Dodge_ViperGTS_2015Kit0_BackplatePaint_Geo_lodA001: THREE.Mesh
    Dodge_ViperGTS_2015RearLight_Geo_lodA001: THREE.Mesh
    Dodge_ViperGTS_2015Light_Geo_lodA: THREE.Mesh
    Dodge_ViperGTS_2015_Wheel_2Combined3DWheel_3DWheel_Front_L_: THREE.Mesh
    Dodge_ViperGTS_2015_CallipersCombinedCalliperExotic4Callipe002: THREE.Mesh
    Dodge_ViperGTS_2015_Wheel_2Combined3DWheel_3DWheel_Front_L_002: THREE.Mesh
    Dodge_ViperGTS_2015_Wheel_2Combined3DWheel_3DWheel_Front_L_003: THREE.Mesh
    Dodge_ViperGTS_2015_CallipersCombinedCalliperExotic4Callipe001: THREE.Mesh
    Dodge_ViperGTS_2015_Wheel_2Combined3DWheel_3DWheel_Front_L_004: THREE.Mesh
    Dodge_ViperGTS_2015_CallipersCombinedCalliperExotic4Callipe003: THREE.Mesh
    Dodge_ViperGTS_2015_Wheel_2Combined3DWheel_3DWheel_Front_L_005: THREE.Mesh
    Dodge_ViperGTS_2015Window_Geo_lodA001: THREE.Mesh
  }
  materials: {
    Wheels: THREE.MeshPhysicalMaterial
    Caliper: THREE.MeshStandardMaterial
    Engine: THREE.MeshStandardMaterial
    Grille2: THREE.MeshStandardMaterial
    Badge: THREE.MeshPhysicalMaterial
    Paint2: THREE.MeshPhysicalMaterial
    Grille1: THREE.MeshStandardMaterial
    Interior: THREE.MeshStandardMaterial
    Interior2: THREE.MeshStandardMaterial
    Paint: THREE.MeshPhysicalMaterial
    Seatbelt: THREE.MeshStandardMaterial
    Plate: THREE.MeshPhysicalMaterial
    Glass: THREE.MeshPhysicalMaterial
    CarbonFiber: THREE.MeshPhysicalMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    Lights: THREE.MeshStandardMaterial
    ['Wheels.001']: THREE.MeshPhysicalMaterial
    ['Wheels.008']: THREE.MeshPhysicalMaterial
    RearLightCovers: THREE.MeshPhysicalMaterial
  }
}

export function Viper(props: any) {
  const { nodes, materials } = useGLTF('models/viper.glb') as GLTFResult

  useEffect(() => {
    // car paint
    Object.entries(materials).map((material) => {
      if (material[0] == "Paint") {
        material[1].color = new THREE.Color(props.color.hexCode);
      }
      material[1].needsUpdate = true;
    });
  }, [materials, props]);

  return (
    <group {...props} dispose={null} scale={4} position={[0, -1.48, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015_Wheel_2Combined3DWheel_3DWheel_Front_L_Inst.geometry}
        material={materials.Wheels}
        position={[-0.767, 0.16, -1.256]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dodge_ViperGTS_2015_CallipersCombinedCalliperExotic4Callipe.geometry}
          material={materials.Caliper}
          position={[-0.011, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dodge_ViperGTS_2015_Wheel_2Combined3DWheel_3DWheel_Front_L_001.geometry}
          material={materials.Wheels}
          position={[0.002, -0.001, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015Engine_Geo_lodA.geometry}
        material={materials.Engine}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015Grille2_Geo_lodA.geometry}
        material={materials.Grille2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015Kit0_Badge_Geo_lodA.geometry}
        material={materials.Badge}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015Kit0_Base_Geo_lodA.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015Kit0_Carbon1_Geo_lodA.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015Kit0_Coloured_Geo_lodA.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015Kit0_Grille1_Geo_lodA.geometry}
        material={materials.Grille1}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015Kit0_Interior_Geo_lodA.geometry}
        material={materials.Interior}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015Kit0_InteriorTillingColourZone_Geo_lodA.geometry}
        material={materials.Interior2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015Kit0_Paint_Geo_lodA.geometry}
        material={materials.Paint}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015Kit0_SeatBelt_Geo_lodA.geometry}
        material={materials.Seatbelt}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015ManufacturerPlate_Geo_lodA.geometry}
        material={materials.Plate}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015Window_Geo_lodA.geometry}
        material={materials.Glass}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015Kit0_BackplatePaint_Geo_lodA001.geometry}
        material={materials.CarbonFiber}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015RearLight_Geo_lodA001.geometry}
        material={materials['Material.002']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015Light_Geo_lodA.geometry}
        material={materials.Lights}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015_Wheel_2Combined3DWheel_3DWheel_Front_L_.geometry}
        material={materials.Wheels}
        position={[-0.767, 0.16, 1.251]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dodge_ViperGTS_2015_CallipersCombinedCalliperExotic4Callipe002.geometry}
          material={materials.Caliper}
          position={[-0.016, 0.006, -0.007]}
          rotation={[2.88, 0, 0]}
          scale={-1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dodge_ViperGTS_2015_Wheel_2Combined3DWheel_3DWheel_Front_L_002.geometry}
          material={materials['Wheels.001']}
          position={[0.002, -0.001, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015_Wheel_2Combined3DWheel_3DWheel_Front_L_003.geometry}
        material={materials.Wheels}
        position={[0.767, 0.16, 1.249]}
        rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dodge_ViperGTS_2015_CallipersCombinedCalliperExotic4Callipe001.geometry}
          material={materials.Caliper}
          position={[-0.016, 0.006, -0.007]}
          rotation={[-0.262, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015_Wheel_2Combined3DWheel_3DWheel_Front_L_004.geometry}
        material={materials.Wheels}
        position={[0.767, 0.16, -1.265]}
        rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dodge_ViperGTS_2015_CallipersCombinedCalliperExotic4Callipe003.geometry}
          material={materials.Caliper}
          position={[-0.011, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dodge_ViperGTS_2015_Wheel_2Combined3DWheel_3DWheel_Front_L_005.geometry}
          material={materials['Wheels.008']}
          position={[0.002, -0.001, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dodge_ViperGTS_2015Window_Geo_lodA001.geometry}
        material={materials.RearLightCovers}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('models/viper.glb')