/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
  };
  materials: {
    ["brake_disc.001"]: THREE.MeshStandardMaterial;
    ["brake_disc1.001"]: THREE.MeshStandardMaterial;
    ["carpaint.001"]: THREE.MeshPhysicalMaterial;
    ["numberplate.001"]: THREE.MeshStandardMaterial;
    ["plastic.001"]: THREE.MeshStandardMaterial;
    ["interior.001"]: THREE.MeshPhysicalMaterial;
    ["nothing..001"]: THREE.MeshStandardMaterial;
    ["reflect.003"]: THREE.MeshStandardMaterial;
    ["rubber.001"]: THREE.MeshStandardMaterial;
    ["wheel_metal.002"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["chrome.001"]: THREE.MeshStandardMaterial;
    ["glass.002"]: THREE.MeshStandardMaterial;
    ["lights11.001"]: THREE.MeshStandardMaterial;
    ["misc_metal.002"]: THREE.MeshStandardMaterial;
    ["reflect.002"]: THREE.MeshStandardMaterial;
    ["glass.003"]: THREE.MeshPhysicalMaterial;
    ["tail_lights.001"]: THREE.MeshStandardMaterial;
  };
};

export function SupraRZ(props: any) {
  const { nodes, materials } = useGLTF("model/supra_93.glb") as GLTFResult;
  const carModel = useRef<THREE.Group<THREE.Object3DEventMap>>(null);

  useEffect(() => {
    // enable car shadows
    carModel.current?.traverse((child) => {
      if (child instanceof THREE.Mesh) {
        child.castShadow = true;
        child.receiveShadow = true;
      }
    });

    // car paint
    Object.entries(materials).map((material) => {
      if (material[0] == "carpaint.001") {
        material[1].color = new THREE.Color(props.color.hexCode);
      }
      material[1].needsUpdate = true;
    });
  }, [materials, props]);

  return (
    <group
      {...props}
      dispose={null}
      ref={carModel}
      rotation={[0, -1.1, 0]}
      position={[0, -1.75, 0]}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials["brake_disc.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials["brake_disc1.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials["carpaint.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials["numberplate.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials["plastic.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials["interior.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials["nothing..001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials["reflect.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials["rubber.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={materials["wheel_metal.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials["chrome.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials["glass.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials["lights11.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials["misc_metal.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials["reflect.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials["glass.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials["tail_lights.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("model/supra_93.glb");
