/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Porsche_918Spyder_2015_Wheel_1Combined3DWheel_3DWheel_front_L_I: THREE.Mesh
    Porsche_918SpyderGold_2015CombinedCalliperBodyExotic6_Insta: THREE.Mesh
    Porsche_918Spyder_2015Kit1_Badge_Geo_lodA: THREE.Mesh
    Porsche_918Spyder_2015Kit1_Base_Geo_lodA: THREE.Mesh
    Porsche_918Spyder_2015Kit1_Carbon1_Geo_lodA: THREE.Mesh
    Porsche_918Spyder_2015Kit1_Coloured_Geo_lodA: THREE.Mesh
    Porsche_918Spyder_2015Kit1_Engine_Geo_lodA: THREE.Mesh
    Porsche_918Spyder_2015Kit1_Grille1_Geo_lodA: THREE.Mesh
    Porsche_918Spyder_2015Kit1_Grille2_Geo_lodA: THREE.Mesh
    Porsche_918Spyder_2015Kit1_Grille3_Geo_lodA: THREE.Mesh
    Porsche_918Spyder_2015Kit1_Interior_Geo_lodA: THREE.Mesh
    Porsche_918Spyder_2015Kit1_InteriorTilling_Geo_lodA: THREE.Mesh
    Porsche_918Spyder_2015Kit1_Light_Geo_lodA: THREE.Mesh
    Porsche_918Spyder_2015Kit1_ManufacturerPlate_Geo_lodA: THREE.Mesh
    Porsche_918Spyder_2015Kit1_Paint_Geo_lodA: THREE.Mesh
    Porsche_918Spyder_2015Kit1_SeatBelt_Geo_lodA: THREE.Mesh
    Porsche_918Spyder_2015Kit1_Window_Geo_lodA: THREE.Mesh
    Porsche_918Spyder_2015Kit1_RearLights: THREE.Mesh
    Porsche_918Spyder_2015_Wheel_1Combined3DWheel_3DWheel_front: THREE.Mesh
    Porsche_918SpyderGold_2015CombinedCalliperBodyExotic6_Instance1: THREE.Mesh
    Porsche_918Spyder_2015_Wheel_1Combined3DWheel_3DWheel_front001: THREE.Mesh
    Porsche_918SpyderGold_2015CombinedCalliperBodyExotic6_Insta001: THREE.Mesh
    Porsche_918Spyder_2015_Wheel_1Combined3DWheel_3DWheel_front002: THREE.Mesh
    Porsche_918SpyderGold_2015CombinedCalliperBodyExotic6_Insta002: THREE.Mesh
  }
  materials: {
    Wheel: THREE.MeshPhysicalMaterial
    Caliper: THREE.MeshStandardMaterial
    Badge: THREE.MeshStandardMaterial
    BodyPaint2: THREE.MeshStandardMaterial
    Engine: THREE.MeshStandardMaterial
    Grille1: THREE.MeshStandardMaterial
    Grille2: THREE.MeshStandardMaterial
    Grille3: THREE.MeshStandardMaterial
    Interior: THREE.MeshStandardMaterial
    Interior2: THREE.MeshStandardMaterial
    Lights: THREE.MeshStandardMaterial
    Plate: THREE.MeshStandardMaterial
    BodyPaint: THREE.MeshStandardMaterial
    Seatbelt: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    RearLights: THREE.MeshStandardMaterial
  }
}

export function Porsche918(props: any) {
  const { nodes, materials } = useGLTF('model/918.glb') as GLTFResult

  useEffect(() => {
    // car paint
    Object.entries(materials).map((material) => {
      if (material[0] == "BodyPaint") {
        material[1].color = new THREE.Color(props.color.hexCode);
      }
      material[1].needsUpdate = true;
    });
  }, [materials, props]);

  return (
    <group {...props} dispose={null} scale={4} position={[0, -1.57, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015_Wheel_1Combined3DWheel_3DWheel_front_L_I.geometry}
        material={materials.Wheel}
        position={[0.792, 0.209, 1.283]}
        rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Porsche_918SpyderGold_2015CombinedCalliperBodyExotic6_Insta.geometry}
          material={materials.Caliper}
          position={[-0.001, -0.185, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015Kit1_Badge_Geo_lodA.geometry}
        material={materials.Badge}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015Kit1_Base_Geo_lodA.geometry}
        material={materials.BodyPaint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015Kit1_Carbon1_Geo_lodA.geometry}
        material={materials.BodyPaint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015Kit1_Coloured_Geo_lodA.geometry}
        material={materials.BodyPaint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015Kit1_Engine_Geo_lodA.geometry}
        material={materials.Engine}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015Kit1_Grille1_Geo_lodA.geometry}
        material={materials.Grille1}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015Kit1_Grille2_Geo_lodA.geometry}
        material={materials.Grille2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015Kit1_Grille3_Geo_lodA.geometry}
        material={materials.Grille3}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015Kit1_Interior_Geo_lodA.geometry}
        material={materials.Interior}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015Kit1_InteriorTilling_Geo_lodA.geometry}
        material={materials.Interior2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015Kit1_Light_Geo_lodA.geometry}
        material={materials.Lights}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015Kit1_ManufacturerPlate_Geo_lodA.geometry}
        material={materials.Plate}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015Kit1_Paint_Geo_lodA.geometry}
        material={materials.BodyPaint}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015Kit1_SeatBelt_Geo_lodA.geometry}
        material={materials.Seatbelt}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015Kit1_Window_Geo_lodA.geometry}
        material={materials.Glass}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015Kit1_RearLights.geometry}
        material={materials.RearLights}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015_Wheel_1Combined3DWheel_3DWheel_front.geometry}
        material={materials.Wheel}
        position={[0.792, 0.209, -1.459]}
        rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Porsche_918SpyderGold_2015CombinedCalliperBodyExotic6_Instance1.geometry}
          material={materials.Caliper}
          position={[-0.001, -0.185, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015_Wheel_1Combined3DWheel_3DWheel_front001.geometry}
        material={materials.Wheel}
        position={[-0.792, 0.209, 1.283]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Porsche_918SpyderGold_2015CombinedCalliperBodyExotic6_Insta001.geometry}
          material={materials.Caliper}
          position={[-0.001, -0.185, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_918Spyder_2015_Wheel_1Combined3DWheel_3DWheel_front002.geometry}
        material={materials.Wheel}
        position={[-0.792, 0.209, -1.459]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Porsche_918SpyderGold_2015CombinedCalliperBodyExotic6_Insta002.geometry}
          material={materials.Caliper}
          position={[-0.001, -0.185, 0]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('model/918.glb')