/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { useEffect } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Pagani_ZondaCinqueCoupe_2009_Wheel_1Combined3DWheel_3DWheel_Fro: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009_CallipersCombinedCalliperExotic6Ca: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009Badge_Geo_lodA: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009Base_Geo_lodA: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009Carbon1_Geo_lodA: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009Carbon1Details_Geo_lodA: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009Coloured_Geo_lodA: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009Engine_Geo_lodA: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009Grille1_Geo_lodA: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009Grille2_Geo_lodA: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009Grille3_Geo_lodA: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009Grille4_Geo_lodA: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009Interior_Geo_lodA: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009ManufacturerPlate_Geo_lodA: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009Paint_Geo_lodA: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009SeatBelt_Geo_lodA: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009SpecularTint_Geo_lodA: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009Textured2_Geo_lodA: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009Textured_Geo_lodA: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009Window_Geo_lodA: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009Stripe: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009_Wheel_1Combined3DWheel_3DWheel: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009_CallipersCombinedCalliperExotic4Ca: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009_Wheel_1Combined3DWheel_3DWheel001: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009_CallipersCombinedCalliperExoti: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009_Wheel_1Combined3DWheel_3DWheel002: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009_CallipersCombinedCalliperExoti001: THREE.Mesh
    Pagani_ZondaCinqueCoupe_2009Light_Geo_lodA: THREE.Mesh
  }
  materials: {
    Wheels: THREE.MeshPhysicalMaterial
    Caliper: THREE.MeshStandardMaterial
    Badge: THREE.MeshPhysicalMaterial
    Paint2: THREE.MeshPhysicalMaterial
    CarbonFiber: THREE.MeshPhysicalMaterial
    Engine: THREE.MeshStandardMaterial
    Grille1: THREE.MeshStandardMaterial
    Grille2: THREE.MeshStandardMaterial
    Grille3: THREE.MeshStandardMaterial
    Grille4: THREE.MeshStandardMaterial
    Interior: THREE.MeshStandardMaterial
    Plate: THREE.MeshPhysicalMaterial
    Paint: THREE.MeshPhysicalMaterial
    Seatbelt: THREE.MeshStandardMaterial
    Glass: THREE.MeshPhysicalMaterial
    Stripe: THREE.MeshPhysicalMaterial
    Lights: THREE.MeshStandardMaterial
  }
}

export function ZondaCinque(props: any) {
    const { nodes, materials } = useGLTF('models/zonda_cinque.glb') as GLTFResult
  
    useEffect(() => {
      // car paint
      Object.entries(materials).map((material) => {
        if (material[0] == "Paint") {
          material[1].color = new THREE.Color(props.color.hexCode);
        }
        material[1].needsUpdate = true;
      });
    }, [materials, props]);
  
    return (
      <group {...props} dispose={null} scale={4} position={[0, -1.96, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009_Wheel_1Combined3DWheel_3DWheel_Fro.geometry}
        material={materials.Wheels}
        position={[-0.752, 0.295, 1.311]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.85, -1, -1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pagani_ZondaCinqueCoupe_2009_CallipersCombinedCalliperExotic6Ca.geometry}
          material={materials.Caliper}
          position={[-0.002, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009Badge_Geo_lodA.geometry}
        material={materials.Badge}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009Base_Geo_lodA.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009Carbon1_Geo_lodA.geometry}
        material={materials.CarbonFiber}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009Carbon1Details_Geo_lodA.geometry}
        material={materials.CarbonFiber}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009Coloured_Geo_lodA.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009Engine_Geo_lodA.geometry}
        material={materials.Engine}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009Grille1_Geo_lodA.geometry}
        material={materials.Grille1}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009Grille2_Geo_lodA.geometry}
        material={materials.Grille2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009Grille3_Geo_lodA.geometry}
        material={materials.Grille3}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009Grille4_Geo_lodA.geometry}
        material={materials.Grille4}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009Interior_Geo_lodA.geometry}
        material={materials.Interior}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009ManufacturerPlate_Geo_lodA.geometry}
        material={materials.Plate}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009Paint_Geo_lodA.geometry}
        material={materials.Paint}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009SeatBelt_Geo_lodA.geometry}
        material={materials.Seatbelt}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009SpecularTint_Geo_lodA.geometry}
        material={nodes.Pagani_ZondaCinqueCoupe_2009SpecularTint_Geo_lodA.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009Textured2_Geo_lodA.geometry}
        material={nodes.Pagani_ZondaCinqueCoupe_2009Textured2_Geo_lodA.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009Textured_Geo_lodA.geometry}
        material={nodes.Pagani_ZondaCinqueCoupe_2009Textured_Geo_lodA.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009Window_Geo_lodA.geometry}
        material={materials.Glass}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009Stripe.geometry}
        material={materials.Stripe}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009_Wheel_1Combined3DWheel_3DWheel.geometry}
        material={materials.Wheels}
        position={[-0.764, 0.295, -1.478]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pagani_ZondaCinqueCoupe_2009_CallipersCombinedCalliperExotic4Ca.geometry}
          material={materials.Caliper}
          position={[0.044, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009_Wheel_1Combined3DWheel_3DWheel001.geometry}
        material={materials.Wheels}
        position={[0.764, 0.295, -1.478]}
        rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pagani_ZondaCinqueCoupe_2009_CallipersCombinedCalliperExoti.geometry}
          material={materials.Caliper}
          position={[0.044, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009_Wheel_1Combined3DWheel_3DWheel002.geometry}
        material={materials.Wheels}
        position={[0.752, 0.295, 1.311]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.85, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pagani_ZondaCinqueCoupe_2009_CallipersCombinedCalliperExoti001.geometry}
          material={materials.Caliper}
          position={[-0.002, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pagani_ZondaCinqueCoupe_2009Light_Geo_lodA.geometry}
        material={materials.Lights}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('models/zonda_cinque.glb')