/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    amdb11_brakedisc_FR001_amdb11_badging002_0: THREE.Mesh
    amdb11_brakedisc_FR001_amdb11_brake002_0: THREE.Mesh
    amdb11_brakedisc_FR001_amdb11_caliper002_0: THREE.Mesh
    amdb11_brakedisc_FR001_amdb11_misc002_0: THREE.Mesh
    amdb11_brakedisc_FR001_amdb11_misc_chrome002_0: THREE.Mesh
    amdb11_brakedisc_FR002_amdb11_badging002_0: THREE.Mesh
    amdb11_brakedisc_FR002_amdb11_brake002_0: THREE.Mesh
    amdb11_brakedisc_FR002_amdb11_caliper002_0: THREE.Mesh
    amdb11_brakedisc_FR002_amdb11_misc002_0: THREE.Mesh
    amdb11_brakedisc_FR002_amdb11_misc_chrome002_0: THREE.Mesh
    amdb11_brakedisc_FR003_amdb11_badging002_0: THREE.Mesh
    amdb11_brakedisc_FR003_amdb11_brake002_0: THREE.Mesh
    amdb11_brakedisc_FR003_amdb11_caliper002_0: THREE.Mesh
    amdb11_brakedisc_FR003_amdb11_misc002_0: THREE.Mesh
    amdb11_brakedisc_FR003_amdb11_misc_chrome002_0: THREE.Mesh
    amdb11_brakedisc_FR004_amdb11_badging002_0: THREE.Mesh
    amdb11_brakedisc_FR004_amdb11_brake002_0: THREE.Mesh
    amdb11_brakedisc_FR004_amdb11_caliper002_0: THREE.Mesh
    amdb11_brakedisc_FR004_amdb11_misc002_0: THREE.Mesh
    amdb11_brakedisc_FR004_amdb11_misc_chrome002_0: THREE.Mesh
    ['Object_4001_Scene_-_Root002_0']: THREE.Mesh
    ['Object_4002_Scene_-_Root002_0']: THREE.Mesh
    ['Object_4003_Scene_-_Root002_0']: THREE.Mesh
    ['Object_4004_Scene_-_Root002_0']: THREE.Mesh
    ['SL63_badge-F-AMG_body6_0']: THREE.Mesh
    ['SL63_body_SL63_black-leather_0']: THREE.Mesh
    SL63_body_SL63_black_0: THREE.Mesh
    SL63_body_SL63_carbon_0: THREE.Mesh
    SL63_body_SL63_carpet_0: THREE.Mesh
    SL63_body_SL63_paint_0: THREE.Mesh
    SL63_body_SL63_plastic_0: THREE.Mesh
    SL63_body_SL63_silver_0: THREE.Mesh
    SL63_body_SL63_speakers_0: THREE.Mesh
    SL63_body_SL63_stitching_0: THREE.Mesh
    SL63_brakepedal_SL63_silver_0: THREE.Mesh
    SL63_bumper_F_SL63_black_0: THREE.Mesh
    SL63_bumper_F_SL63_carbon_0: THREE.Mesh
    SL63_bumper_F_SL63_paint_0: THREE.Mesh
    SL63_bumper_F_SL63_silver_0: THREE.Mesh
    SL63_bumper_R_SL63_black_0: THREE.Mesh
    SL63_bumper_R_SL63_paint_0: THREE.Mesh
    SL63_bumperbar_F_SL63_radiatorsupp_0: THREE.Mesh
    ['SL63_dash-crb_seat5_0']: THREE.Mesh
    ['SL63_dash-crb_SL63_ambiente-on_0']: THREE.Mesh
    ['SL63_dash-crb_SL63_black-leather_0']: THREE.Mesh
    ['SL63_dash-crb_SL63_black_0']: THREE.Mesh
    ['SL63_dash-crb_SL63_carbon_0']: THREE.Mesh
    ['SL63_dash-crb_SL63_interiorSymbs_0']: THREE.Mesh
    ['SL63_dash-crb_SL63_silver_0']: THREE.Mesh
    ['SL63_dash-crb_SL63_stitching_0']: THREE.Mesh
    ['SL63_dash-crb_SL63_white-leather_0']: THREE.Mesh
    SL63_diff_SL63_underbody_0: THREE.Mesh
    SL63_diff_F_SL63_underbody_0: THREE.Mesh
    SL63_diffuser_R_SL63_black_0: THREE.Mesh
    SL63_diffuser_R_SL63_carbon_0: THREE.Mesh
    SL63_diffuser_R_SL63_darkred_0: THREE.Mesh
    ['SL63_diffuser_R-crb_SL63_black_0']: THREE.Mesh
    ['SL63_diffuser_R-crb_SL63_carbon_0']: THREE.Mesh
    ['SL63_diffuser_R-crb_SL63_darkred_0']: THREE.Mesh
    ['SL63_door_L_SL63_black-leather_0']: THREE.Mesh
    SL63_door_L_SL63_black_0: THREE.Mesh
    SL63_door_L_SL63_paint_0: THREE.Mesh
    SL63_door_L_SL63_silver_0: THREE.Mesh
    ['SL63_door_R_SL63_black-leather_0']: THREE.Mesh
    SL63_door_R_SL63_black_0: THREE.Mesh
    SL63_door_R_SL63_paint_0: THREE.Mesh
    SL63_door_R_SL63_silver_0: THREE.Mesh
    ['SL63_doorglass_L-tint_SL63_tinted-glass_0']: THREE.Mesh
    ['SL63_doorglass_R-tint_SL63_tinted-glass_0']: THREE.Mesh
    ['SL63_doorpanel_L_SL63_ambiente-on_0']: THREE.Mesh
    ['SL63_doorpanel_L_SL63_black-leather_0']: THREE.Mesh
    SL63_doorpanel_L_SL63_black_0: THREE.Mesh
    SL63_doorpanel_L_SL63_carbon_0: THREE.Mesh
    SL63_doorpanel_L_SL63_interiorSymbs_0: THREE.Mesh
    SL63_doorpanel_L_SL63_plastic_0: THREE.Mesh
    SL63_doorpanel_L_SL63_silver_0: THREE.Mesh
    SL63_doorpanel_L_SL63_speakers_0: THREE.Mesh
    ['SL63_doorpanel_L_SL63_white-leather_0']: THREE.Mesh
    ['SL63_doorpanel_R_SL63_ambiente-on_0']: THREE.Mesh
    ['SL63_doorpanel_R_SL63_black-leather_0']: THREE.Mesh
    SL63_doorpanel_R_SL63_black_0: THREE.Mesh
    SL63_doorpanel_R_SL63_carbon_0: THREE.Mesh
    SL63_doorpanel_R_SL63_interiorSymbs_0: THREE.Mesh
    SL63_doorpanel_R_SL63_plastic_0: THREE.Mesh
    SL63_doorpanel_R_SL63_silver_0: THREE.Mesh
    SL63_doorpanel_R_SL63_speakers_0: THREE.Mesh
    ['SL63_doorpanel_R_SL63_white-leather_0']: THREE.Mesh
    SL63_driveshaft_SL63_underbody_0: THREE.Mesh
    SL63_driveshaft_F_SL63_underbody_0: THREE.Mesh
    ['SL63_engine-63V8_chassis14_0']: THREE.Mesh
    ['SL63_engine-63V8_chassis2_0']: THREE.Mesh
    ['SL63_engine-63V8_chassis3_0']: THREE.Mesh
    ['SL63_engine-63V8_chassis7_0']: THREE.Mesh
    ['SL63_engine-63V8_chassis8_0']: THREE.Mesh
    ['SL63_engine-63V8_engine16_0']: THREE.Mesh
    ['SL63_engine-63V8_SL63_b_0']: THREE.Mesh
    ['SL63_engine-63V8-turbos_chassis2_0']: THREE.Mesh
    ['SL63_engine-63V8-turbos_chassis7_0']: THREE.Mesh
    ['SL63_engine-63V8-turbos_engine12_0']: THREE.Mesh
    ['SL63_engine-63V8-turbos_engine15_0']: THREE.Mesh
    ['SL63_engine-63V8-turbos_SL63_b_0']: THREE.Mesh
    SL63_enginebay_SL63_black_0: THREE.Mesh
    SL63_enginebay_SL63_silver_0: THREE.Mesh
    SL63_exhaust_L_SL63_underbody_0: THREE.Mesh
    SL63_exhaust_R_SL63_underbody_0: THREE.Mesh
    SL63_exhausttips_SL63_black_0: THREE.Mesh
    SL63_exhausttips_SL63_silver_0: THREE.Mesh
    SL63_fender_L_SL63_black_0: THREE.Mesh
    SL63_fender_L_SL63_carbon_0: THREE.Mesh
    SL63_fender_L_SL63_dark_0: THREE.Mesh
    SL63_fender_L_SL63_paint_0: THREE.Mesh
    SL63_fender_L_SL63_silver_0: THREE.Mesh
    SL63_fender_R_SL63_black_0: THREE.Mesh
    SL63_fender_R_SL63_carbon_0: THREE.Mesh
    SL63_fender_R_SL63_dark_0: THREE.Mesh
    SL63_fender_R_SL63_paint_0: THREE.Mesh
    SL63_fender_R_SL63_silver_0: THREE.Mesh
    ['SL63_floormat-L_SL63_carpet_0']: THREE.Mesh
    ['SL63_floormat-L_SL63_silver_0']: THREE.Mesh
    ['SL63_floormat-R_SL63_carpet_0']: THREE.Mesh
    ['SL63_floormat-R_SL63_silver_0']: THREE.Mesh
    SL63_fueltank_SL63_underbody_0: THREE.Mesh
    SL63_gaspedal_SL63_silver_0: THREE.Mesh
    SL63_gauges_SL63_black_0: THREE.Mesh
    SL63_gauges_SL63_gauges_screen_0: THREE.Mesh
    ['Sl63_grille-F-AMG_SL63_black_0']: THREE.Mesh
    ['Sl63_grille-F-AMG_SL63_carbon_0']: THREE.Mesh
    ['Sl63_grille-F-AMG_SL63_silver_0']: THREE.Mesh
    SL63_halfshaft_F_SL63_underbody_0: THREE.Mesh
    SL63_halfshaft_R_SL63_underbody_0: THREE.Mesh
    SL63_headlight_L_SL63_black001_0: THREE.Mesh
    ['SL63_headlight_L_SL63_lowbeams-F001_0']: THREE.Mesh
    ['SL63_headlight_L_SL63_runninglight-Fl_0']: THREE.Mesh
    ['SL63_headlight_L_SL63_runninglight-Fr_0']: THREE.Mesh
    SL63_headlight_L_SL63_silver_0: THREE.Mesh
    SL63_headlight_L_SL65_cornerlight_left_0: THREE.Mesh
    SL63_headlight_L_SL65_cornerlight_right_0: THREE.Mesh
    ['SL63_headlightglass_R-tint_SL63_tinted-glass001_0']: THREE.Mesh
    SL63_heatshield_SL63_underbody_0: THREE.Mesh
    SL63_hood_SL63_black_0: THREE.Mesh
    SL63_hood_SL63_carbon_0: THREE.Mesh
    SL63_hood_SL63_paint_0: THREE.Mesh
    SL63_hood_SL63_silver_0: THREE.Mesh
    SL63_hub_F_SL63_underbody_0: THREE.Mesh
    SL63_hub_R_SL63_underbody_0: THREE.Mesh
    SL63_intmirror_SL63_mirror_0: THREE.Mesh
    SL63_intmirror_wheel3_0: THREE.Mesh
    SL63_lettering_trunk_amg_SL63_silver_0: THREE.Mesh
    SL63_lettering_trunk_SL63_SL63_silver_0: THREE.Mesh
    SL63_logo_R_SL63_silver_0: THREE.Mesh
    SL63_lowerarm_F_a_SL63_underbody_0: THREE.Mesh
    SL63_lowerarm_F_b_SL63_underbody_0: THREE.Mesh
    SL63_lowerarm_R_SL63_underbody_0: THREE.Mesh
    SL63_mirror_L_door_lf_ok9_0: THREE.Mesh
    SL63_mirror_L_SL63_black_0: THREE.Mesh
    SL63_mirror_L_SL63_mirror_0: THREE.Mesh
    SL63_mirror_L_SL63_signal_L_0: THREE.Mesh
    SL63_mirror_L_SL63_silver_0: THREE.Mesh
    SL63_mirror_R_SL63_black_0: THREE.Mesh
    SL63_mirror_R_SL63_mirror_0: THREE.Mesh
    SL63_mirror_R_SL63_signal_L_0: THREE.Mesh
    SL63_mirror_R_SL63_silver_0: THREE.Mesh
    SL63_muffler_L_bastion_mechanical_0: THREE.Mesh
    SL63_muffler_R_bastion_mechanical_0: THREE.Mesh
    ['SL63_navi_SL63_black-leather_0']: THREE.Mesh
    ['SL63_navi_SL63_GPS-Screen_0']: THREE.Mesh
    SL63_navi_SL63_interiorSymbs_0: THREE.Mesh
    SL63_navi_SL63_silver_0: THREE.Mesh
    ['SL63_paddles_SL63_black-leather_0']: THREE.Mesh
    SL63_paddles_wheel3_0: THREE.Mesh
    SL63_radiator_SL63_radiatorsupp_0: THREE.Mesh
    SL63_radsupport_SL63_underbody_0: THREE.Mesh
    ['SL63_rearseats_SL63_black-leather_0']: THREE.Mesh
    SL63_rearseats_SL63_black_0: THREE.Mesh
    SL63_rearseats_SL63_darkred_0: THREE.Mesh
    SL63_rearseats_SL63_silver_0: THREE.Mesh
    ['SL63_rearseats_SL63_white-leather_0']: THREE.Mesh
    ['SL63_seat_FL_SL63_black-leather_0']: THREE.Mesh
    SL63_seat_FL_SL63_darkred_0: THREE.Mesh
    SL63_seat_FL_SL63_silver_0: THREE.Mesh
    SL63_seat_FL_SL63_stitching_0: THREE.Mesh
    ['SL63_seat_FL_SL63_white-leather_0']: THREE.Mesh
    ['SL63_seat_FR_SL63_black-leather_0']: THREE.Mesh
    SL63_seat_FR_SL63_darkred_0: THREE.Mesh
    SL63_seat_FR_SL63_silver_0: THREE.Mesh
    SL63_seat_FR_SL63_stitching_0: THREE.Mesh
    ['SL63_seat_FR_SL63_white-leather_0']: THREE.Mesh
    SL63_shifter_A_SL63_black_0: THREE.Mesh
    SL63_shifter_A_SL63_interiorSymbs_0: THREE.Mesh
    ['SL63_shiftlight-dash_shiftlight_multi_0']: THREE.Mesh
    ['SL63_shiftlight-dash_shiftlight_multi_l0_0']: THREE.Mesh
    ['SL63_shiftlight-dash_shiftlight_multi_l1_0']: THREE.Mesh
    ['SL63_shiftlight-dash_shiftlight_multi_l2_0']: THREE.Mesh
    ['SL63_shiftlight-dash_shiftlight_multi_l3_0']: THREE.Mesh
    ['SL63_shiftlight-dash_shiftlight_multi_l4_0']: THREE.Mesh
    ['SL63_shiftlight-dash_shiftlight_multi_l5_0']: THREE.Mesh
    ['SL63_shiftlight-dash_shiftlight_multi_l6_0']: THREE.Mesh
    ['SL63_shiftlight-dash_shiftlight_multi_l7_0']: THREE.Mesh
    SL63_shock_R_SL63_underbody_0: THREE.Mesh
    ['SL63_sideskirt-L-crb_SL63_carbon_0']: THREE.Mesh
    ['SL63_sideskirt-L-crb_SL63_paint_0']: THREE.Mesh
    ['SL63_sideskirt-R-crb_SL63_carbon_0']: THREE.Mesh
    ['SL63_sideskirt-R-crb_SL63_paint_0']: THREE.Mesh
    SL63_signalstalk_SL63_black_0: THREE.Mesh
    SL63_signalstalk_SL63_interiorSymbs_0: THREE.Mesh
    ['SL63_spoiler-R_SL63_paint_0']: THREE.Mesh
    ['SL63_spoiler-R_SL63_silver_0']: THREE.Mesh
    SL63_spring_R_SL63_underbody_0: THREE.Mesh
    SL63_steeringbox_SL63_underbody_0: THREE.Mesh
    ['SL63_steeringwheel-crb_SL63_black-leather_0']: THREE.Mesh
    ['SL63_steeringwheel-crb_SL63_black_0']: THREE.Mesh
    ['SL63_steeringwheel-crb_SL63_carbon_0']: THREE.Mesh
    ['SL63_steeringwheel-crb_SL63_steerSymbs_0']: THREE.Mesh
    ['SL63_steeringwheel-crb_SL63_white-leather_0']: THREE.Mesh
    SL63_strut_F_SL63_underbody_0: THREE.Mesh
    SL63_subframe_F_SL63_underbody_0: THREE.Mesh
    SL63_subframe_R_SL63_underbody_0: THREE.Mesh
    ['SL63_sunvisor_SL63_black-leather_0']: THREE.Mesh
    SL63_swaybar_F_SL63_underbody_0: THREE.Mesh
    SL63_swaybar_R_SL63_underbody_0: THREE.Mesh
    ['SL63_taillight_L_SL63_beams-R_0']: THREE.Mesh
    SL63_taillight_L_SL63_brakelight_0: THREE.Mesh
    SL63_taillight_L_SL63_darkred_0: THREE.Mesh
    SL63_taillight_L_SL63_plastic_0: THREE.Mesh
    SL63_taillight_L_SL63_reverselight_0: THREE.Mesh
    ['SL63_taillight_L_SL63_runninglight-R_0']: THREE.Mesh
    SL63_taillight_L_SL63_signal_L_6_0: THREE.Mesh
    SL63_taillight_L_SL63_silver_0: THREE.Mesh
    ['SL63_taillight_R_SL63_beams-R_0']: THREE.Mesh
    SL63_taillight_R_SL63_brakelight_0: THREE.Mesh
    SL63_taillight_R_SL63_darkred_0: THREE.Mesh
    SL63_taillight_R_SL63_plastic_0: THREE.Mesh
    SL63_taillight_R_SL63_reverselight_0: THREE.Mesh
    ['SL63_taillight_R_SL63_runninglight-R_0']: THREE.Mesh
    SL63_taillight_R_SL63_signal_R_10_0: THREE.Mesh
    SL63_taillight_R_SL63_signal_R_11_0: THREE.Mesh
    SL63_taillight_R_SL63_signal_R_12_0: THREE.Mesh
    SL63_taillight_R_SL63_signal_R_13_0: THREE.Mesh
    SL63_taillight_R_SL63_signal_R_14_0: THREE.Mesh
    SL63_taillight_R_SL63_signal_R_15_0: THREE.Mesh
    SL63_taillight_R_SL63_signal_R_1_0: THREE.Mesh
    SL63_taillight_R_SL63_signal_R_2_0: THREE.Mesh
    SL63_taillight_R_SL63_signal_R_3_0: THREE.Mesh
    SL63_taillight_R_SL63_signal_R_4_0: THREE.Mesh
    SL63_taillight_R_SL63_signal_R_5_0: THREE.Mesh
    SL63_taillight_R_SL63_signal_R_6_0: THREE.Mesh
    SL63_taillight_R_SL63_signal_R_7_0: THREE.Mesh
    SL63_taillight_R_SL63_signal_R_8_0: THREE.Mesh
    SL63_taillight_R_SL63_signal_R_9_0: THREE.Mesh
    SL63_taillight_R_SL63_silver_0: THREE.Mesh
    ['SL63_taillightglass_L-tint_SL63_tinted-glass_0']: THREE.Mesh
    ['SL63_taillightglass_R-tint_SL63_tinted-glass_0']: THREE.Mesh
    SL63_tierod_F_SL63_underbody_0: THREE.Mesh
    SL63_tierod_R_SL63_underbody_0: THREE.Mesh
    SL63_transfercase_SL63_underbody_0: THREE.Mesh
    SL63_transmission_SL63_underbody_0: THREE.Mesh
    SL63_trunk_SL63_black_0: THREE.Mesh
    SL63_trunk_SL63_brakelight_0: THREE.Mesh
    SL63_trunk_SL63_paint_0: THREE.Mesh
    SL63_trunk_SL63_silver_0: THREE.Mesh
    ['SL63_tub-RL_bastion_mechanical_0']: THREE.Mesh
    ['SL63_tub-RR_bastion_mechanical_0']: THREE.Mesh
    SL63_tubs_SL63_underbody_0: THREE.Mesh
    SL63_turbos_SL63_black_0: THREE.Mesh
    SL63_turbos_SL63_silver_0: THREE.Mesh
    SL63_underbody_SL63_underbody_0: THREE.Mesh
    SL63_upperarm_R_SL63_underbody_0: THREE.Mesh
    SL63_wheel_SL63_black_0: THREE.Mesh
    SL63_wheel_SL63_silver_0: THREE.Mesh
    SL63_wheel001_SL63_black_0: THREE.Mesh
    SL63_wheel001_SL63_silver_0: THREE.Mesh
    SL63_wheel002_SL63_black_0: THREE.Mesh
    SL63_wheel002_SL63_silver_0: THREE.Mesh
    SL63_wheel003_SL63_black_0: THREE.Mesh
    SL63_wheel003_SL63_silver_0: THREE.Mesh
    ['SL63_windshield-tint_SL63_tinted-glass_0']: THREE.Mesh
    SL63_wipers_SL63_black_0: THREE.Mesh
  }
  materials: {
    ['amdb11_badging.002']: THREE.MeshStandardMaterial
    ['amdb11_brake.002']: THREE.MeshStandardMaterial
    ['amdb11_caliper.002']: THREE.MeshStandardMaterial
    ['amdb11_misc.002']: THREE.MeshStandardMaterial
    ['amdb11_misc_chrome.002']: THREE.MeshStandardMaterial
    ['Scene_-_Root.002']: THREE.MeshStandardMaterial
    ['body.6']: THREE.MeshStandardMaterial
    ['SL63_black-leather']: THREE.MeshStandardMaterial
    SL63_black: THREE.MeshStandardMaterial
    SL63_carbon: THREE.MeshStandardMaterial
    SL63_carpet: THREE.MeshStandardMaterial
    SL63_paint: THREE.MeshPhysicalMaterial
    SL63_plastic: THREE.MeshStandardMaterial
    SL63_silver: THREE.MeshStandardMaterial
    SL63_speakers: THREE.MeshStandardMaterial
    SL63_stitching: THREE.MeshStandardMaterial
    ['SL63_silver.001']: THREE.MeshStandardMaterial
    SL63_radiatorsupp: THREE.MeshStandardMaterial
    ['seat.5']: THREE.MeshStandardMaterial
    ['SL63_ambiente-on']: THREE.MeshStandardMaterial
    SL63_interiorSymbs: THREE.MeshStandardMaterial
    ['SL63_white-leather']: THREE.MeshStandardMaterial
    SL63_underbody: THREE.MeshStandardMaterial
    SL63_darkred: THREE.MeshStandardMaterial
    ['SL63_tinted-glass']: THREE.MeshStandardMaterial
    ['chassis.14']: THREE.MeshStandardMaterial
    ['chassis.2']: THREE.MeshStandardMaterial
    ['chassis.3']: THREE.MeshStandardMaterial
    ['chassis.7']: THREE.MeshStandardMaterial
    ['chassis.8']: THREE.MeshStandardMaterial
    ['engine.16']: THREE.MeshStandardMaterial
    SL63_b: THREE.MeshStandardMaterial
    ['engine.12']: THREE.MeshStandardMaterial
    ['engine.15']: THREE.MeshStandardMaterial
    SL63_dark: THREE.MeshStandardMaterial
    SL63_gauges_screen: THREE.MeshStandardMaterial
    ['SL63_black.002']: THREE.MeshStandardMaterial
    ['SL63_lowbeams-F.001']: THREE.MeshStandardMaterial
    ['SL63_runninglight-Fl']: THREE.MeshStandardMaterial
    ['SL63_runninglight-Fr']: THREE.MeshStandardMaterial
    SL65_cornerlight_left: THREE.MeshStandardMaterial
    SL65_cornerlight_right: THREE.MeshStandardMaterial
    ['SL63_tinted-glass.001']: THREE.MeshStandardMaterial
    ['SL63_black.001']: THREE.MeshStandardMaterial
    ['SL63_carbon.001']: THREE.MeshStandardMaterial
    SL63_mirror: THREE.MeshStandardMaterial
    ['wheel.3']: THREE.MeshStandardMaterial
    ['door_lf_ok.9']: THREE.MeshStandardMaterial
    SL63_signal_L: THREE.MeshStandardMaterial
    bastion_mechanical: THREE.MeshStandardMaterial
    ['SL63_GPS-Screen']: THREE.MeshStandardMaterial
    shiftlight_multi: THREE.MeshStandardMaterial
    shiftlight_multi_l0: THREE.MeshStandardMaterial
    shiftlight_multi_l1: THREE.MeshStandardMaterial
    shiftlight_multi_l2: THREE.MeshStandardMaterial
    shiftlight_multi_l3: THREE.MeshStandardMaterial
    shiftlight_multi_l4: THREE.MeshStandardMaterial
    shiftlight_multi_l5: THREE.MeshStandardMaterial
    shiftlight_multi_l6: THREE.MeshStandardMaterial
    shiftlight_multi_l7: THREE.MeshStandardMaterial
    SL63_steerSymbs: THREE.MeshStandardMaterial
    ['SL63_beams-R']: THREE.MeshStandardMaterial
    SL63_brakelight: THREE.MeshStandardMaterial
    SL63_reverselight: THREE.MeshStandardMaterial
    ['SL63_runninglight-R']: THREE.MeshStandardMaterial
    SL63_signal_L_6: THREE.MeshStandardMaterial
    SL63_signal_R_10: THREE.MeshStandardMaterial
    SL63_signal_R_11: THREE.MeshStandardMaterial
    SL63_signal_R_12: THREE.MeshStandardMaterial
    SL63_signal_R_13: THREE.MeshStandardMaterial
    SL63_signal_R_14: THREE.MeshStandardMaterial
    SL63_signal_R_15: THREE.MeshStandardMaterial
    SL63_signal_R_1: THREE.MeshStandardMaterial
    SL63_signal_R_2: THREE.MeshStandardMaterial
    SL63_signal_R_3: THREE.MeshStandardMaterial
    SL63_signal_R_4: THREE.MeshStandardMaterial
    SL63_signal_R_5: THREE.MeshStandardMaterial
    SL63_signal_R_6: THREE.MeshStandardMaterial
    SL63_signal_R_7: THREE.MeshStandardMaterial
    SL63_signal_R_8: THREE.MeshStandardMaterial
    SL63_signal_R_9: THREE.MeshStandardMaterial
  }
}

export function SL63(props: any) {
  const { nodes, materials } = useGLTF('model/sl63.glb') as GLTFResult

  useEffect(() => {
    // car paint
    Object.entries(materials).map((material) => {
      if (material[0] == "SL63_paint") {
        material[1].color = new THREE.Color(props.color.hexCode);
      }
      material[1].needsUpdate = true;
    });
  }, [materials, props]);

  return (
    <group {...props} dispose={null}>
    <group scale={0.035} rotation={[0, -1.1, 0]} position={[0, -1.682, 0]}>
        <group
          position={[76.157, 33.372, -132.584]}
          rotation={[Math.PI / 2, -0.035, Math.PI]}
          scale={[112.663, 96.688, 96.688]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR001_amdb11_badging002_0.geometry}
            material={materials['amdb11_badging.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR001_amdb11_brake002_0.geometry}
            material={materials['amdb11_brake.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR001_amdb11_caliper002_0.geometry}
            material={materials['amdb11_caliper.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR001_amdb11_misc002_0.geometry}
            material={materials['amdb11_misc.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR001_amdb11_misc_chrome002_0.geometry}
            material={materials['amdb11_misc_chrome.002']}
          />
        </group>
        <group
          position={[-75.7, 33.372, 118.575]}
          rotation={[-Math.PI / 2, -0.035, Math.PI]}
          scale={[-112.663, -96.688, -96.688]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR002_amdb11_badging002_0.geometry}
            material={materials['amdb11_badging.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR002_amdb11_brake002_0.geometry}
            material={materials['amdb11_brake.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR002_amdb11_caliper002_0.geometry}
            material={materials['amdb11_caliper.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR002_amdb11_misc002_0.geometry}
            material={materials['amdb11_misc.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR002_amdb11_misc_chrome002_0.geometry}
            material={materials['amdb11_misc_chrome.002']}
          />
        </group>
        <group
          position={[76.157, 33.372, 118.575]}
          rotation={[Math.PI / 2, -0.035, Math.PI]}
          scale={[112.663, 96.688, 96.688]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR003_amdb11_badging002_0.geometry}
            material={materials['amdb11_badging.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR003_amdb11_brake002_0.geometry}
            material={materials['amdb11_brake.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR003_amdb11_caliper002_0.geometry}
            material={materials['amdb11_caliper.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR003_amdb11_misc002_0.geometry}
            material={materials['amdb11_misc.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR003_amdb11_misc_chrome002_0.geometry}
            material={materials['amdb11_misc_chrome.002']}
          />
        </group>
        <group
          position={[-75.7, 33.372, -132.584]}
          rotation={[-Math.PI / 2, -0.035, Math.PI]}
          scale={[-112.663, -96.688, -96.688]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR004_amdb11_badging002_0.geometry}
            material={materials['amdb11_badging.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR004_amdb11_brake002_0.geometry}
            material={materials['amdb11_brake.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR004_amdb11_caliper002_0.geometry}
            material={materials['amdb11_caliper.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR004_amdb11_misc002_0.geometry}
            material={materials['amdb11_misc.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR004_amdb11_misc_chrome002_0.geometry}
            material={materials['amdb11_misc_chrome.002']}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_body_SL63_black-leather_0'].geometry}
            material={materials['SL63_black-leather']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_body_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_body_SL63_carbon_0.geometry}
            material={materials.SL63_carbon}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_body_SL63_carpet_0.geometry}
            material={materials.SL63_carpet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_body_SL63_paint_0.geometry}
            material={materials.SL63_paint}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_body_SL63_plastic_0.geometry}
            material={materials.SL63_plastic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_body_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_body_SL63_speakers_0.geometry}
            material={materials.SL63_speakers}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_body_SL63_stitching_0.geometry}
            material={materials.SL63_stitching}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_bumper_F_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_bumper_F_SL63_carbon_0.geometry}
            material={materials.SL63_carbon}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_bumper_F_SL63_paint_0.geometry}
            material={materials.SL63_paint}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_bumper_F_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_bumper_R_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_bumper_R_SL63_paint_0.geometry}
            material={materials.SL63_paint}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_dash-crb_seat5_0'].geometry}
            material={materials['seat.5']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_dash-crb_SL63_ambiente-on_0'].geometry}
            material={materials['SL63_ambiente-on']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_dash-crb_SL63_black-leather_0'].geometry}
            material={materials['SL63_black-leather']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_dash-crb_SL63_black_0'].geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_dash-crb_SL63_carbon_0'].geometry}
            material={materials.SL63_carbon}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_dash-crb_SL63_interiorSymbs_0'].geometry}
            material={materials.SL63_interiorSymbs}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_dash-crb_SL63_silver_0'].geometry}
            material={materials.SL63_silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_dash-crb_SL63_stitching_0'].geometry}
            material={materials.SL63_stitching}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_dash-crb_SL63_white-leather_0'].geometry}
            material={materials['SL63_white-leather']}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_diffuser_R_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_diffuser_R_SL63_carbon_0.geometry}
            material={materials.SL63_carbon}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_diffuser_R_SL63_darkred_0.geometry}
            material={materials.SL63_darkred}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_diffuser_R-crb_SL63_black_0'].geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_diffuser_R-crb_SL63_carbon_0'].geometry}
            material={materials.SL63_carbon}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_diffuser_R-crb_SL63_darkred_0'].geometry}
            material={materials.SL63_darkred}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_door_L_SL63_black-leather_0'].geometry}
            material={materials['SL63_black-leather']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_door_L_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_door_L_SL63_paint_0.geometry}
            material={materials.SL63_paint}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_door_L_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_door_R_SL63_black-leather_0'].geometry}
            material={materials['SL63_black-leather']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_door_R_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_door_R_SL63_paint_0.geometry}
            material={materials.SL63_paint}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_door_R_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_doorpanel_L_SL63_ambiente-on_0'].geometry}
            material={materials['SL63_ambiente-on']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_doorpanel_L_SL63_black-leather_0'].geometry}
            material={materials['SL63_black-leather']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_doorpanel_L_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_doorpanel_L_SL63_carbon_0.geometry}
            material={materials.SL63_carbon}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_doorpanel_L_SL63_interiorSymbs_0.geometry}
            material={materials.SL63_interiorSymbs}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_doorpanel_L_SL63_plastic_0.geometry}
            material={materials.SL63_plastic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_doorpanel_L_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_doorpanel_L_SL63_speakers_0.geometry}
            material={materials.SL63_speakers}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_doorpanel_L_SL63_white-leather_0'].geometry}
            material={materials['SL63_white-leather']}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_doorpanel_R_SL63_ambiente-on_0'].geometry}
            material={materials['SL63_ambiente-on']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_doorpanel_R_SL63_black-leather_0'].geometry}
            material={materials['SL63_black-leather']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_doorpanel_R_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_doorpanel_R_SL63_carbon_0.geometry}
            material={materials.SL63_carbon}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_doorpanel_R_SL63_interiorSymbs_0.geometry}
            material={materials.SL63_interiorSymbs}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_doorpanel_R_SL63_plastic_0.geometry}
            material={materials.SL63_plastic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_doorpanel_R_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_doorpanel_R_SL63_speakers_0.geometry}
            material={materials.SL63_speakers}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_doorpanel_R_SL63_white-leather_0'].geometry}
            material={materials['SL63_white-leather']}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_engine-63V8_chassis14_0'].geometry}
            material={materials['chassis.14']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_engine-63V8_chassis2_0'].geometry}
            material={materials['chassis.2']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_engine-63V8_chassis3_0'].geometry}
            material={materials['chassis.3']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_engine-63V8_chassis7_0'].geometry}
            material={materials['chassis.7']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_engine-63V8_chassis8_0'].geometry}
            material={materials['chassis.8']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_engine-63V8_engine16_0'].geometry}
            material={materials['engine.16']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_engine-63V8_SL63_b_0'].geometry}
            material={materials.SL63_b}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_engine-63V8-turbos_chassis2_0'].geometry}
            material={materials['chassis.2']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_engine-63V8-turbos_chassis7_0'].geometry}
            material={materials['chassis.7']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_engine-63V8-turbos_engine12_0'].geometry}
            material={materials['engine.12']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_engine-63V8-turbos_engine15_0'].geometry}
            material={materials['engine.15']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_engine-63V8-turbos_SL63_b_0'].geometry}
            material={materials.SL63_b}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_enginebay_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_enginebay_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_exhausttips_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_exhausttips_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_fender_L_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_fender_L_SL63_carbon_0.geometry}
            material={materials.SL63_carbon}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_fender_L_SL63_dark_0.geometry}
            material={materials.SL63_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_fender_L_SL63_paint_0.geometry}
            material={materials.SL63_paint}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_fender_L_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_fender_R_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_fender_R_SL63_carbon_0.geometry}
            material={materials.SL63_carbon}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_fender_R_SL63_dark_0.geometry}
            material={materials.SL63_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_fender_R_SL63_paint_0.geometry}
            material={materials.SL63_paint}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_fender_R_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_floormat-L_SL63_carpet_0'].geometry}
            material={materials.SL63_carpet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_floormat-L_SL63_silver_0'].geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_floormat-R_SL63_carpet_0'].geometry}
            material={materials.SL63_carpet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_floormat-R_SL63_silver_0'].geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_gauges_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_gauges_SL63_gauges_screen_0.geometry}
            material={materials.SL63_gauges_screen}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Sl63_grille-F-AMG_SL63_black_0'].geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Sl63_grille-F-AMG_SL63_carbon_0'].geometry}
            material={materials.SL63_carbon}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Sl63_grille-F-AMG_SL63_silver_0'].geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_headlight_L_SL63_black001_0.geometry}
            material={materials['SL63_black.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_headlight_L_SL63_lowbeams-F001_0'].geometry}
            material={materials['SL63_lowbeams-F.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_headlight_L_SL63_runninglight-Fl_0'].geometry}
            material={materials['SL63_runninglight-Fl']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_headlight_L_SL63_runninglight-Fr_0'].geometry}
            material={materials['SL63_runninglight-Fr']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_headlight_L_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_headlight_L_SL65_cornerlight_left_0.geometry}
            material={materials.SL65_cornerlight_left}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_headlight_L_SL65_cornerlight_right_0.geometry}
            material={materials.SL65_cornerlight_right}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_hood_SL63_black_0.geometry}
            material={materials['SL63_black.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_hood_SL63_carbon_0.geometry}
            material={materials['SL63_carbon.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_hood_SL63_paint_0.geometry}
            material={materials.SL63_paint}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_hood_SL63_silver_0.geometry}
            material={materials['SL63_silver.001']}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_intmirror_SL63_mirror_0.geometry}
            material={materials.SL63_mirror}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_intmirror_wheel3_0.geometry}
            material={materials['wheel.3']}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_mirror_L_door_lf_ok9_0.geometry}
            material={materials['door_lf_ok.9']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_mirror_L_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_mirror_L_SL63_mirror_0.geometry}
            material={materials.SL63_mirror}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_mirror_L_SL63_signal_L_0.geometry}
            material={materials.SL63_signal_L}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_mirror_L_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_mirror_R_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_mirror_R_SL63_mirror_0.geometry}
            material={materials.SL63_mirror}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_mirror_R_SL63_signal_L_0.geometry}
            material={materials.SL63_signal_L}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_mirror_R_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_navi_SL63_black-leather_0'].geometry}
            material={materials['SL63_black-leather']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_navi_SL63_GPS-Screen_0'].geometry}
            material={materials['SL63_GPS-Screen']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_navi_SL63_interiorSymbs_0.geometry}
            material={materials.SL63_interiorSymbs}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_navi_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group position={[34.524, 76.384, 4.373]} rotation={[-2.88, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_paddles_SL63_black-leather_0'].geometry}
            material={materials['SL63_black-leather']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_paddles_wheel3_0.geometry}
            material={materials['wheel.3']}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_rearseats_SL63_black-leather_0'].geometry}
            material={materials['SL63_black-leather']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_rearseats_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_rearseats_SL63_darkred_0.geometry}
            material={materials.SL63_darkred}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_rearseats_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_rearseats_SL63_white-leather_0'].geometry}
            material={materials['SL63_white-leather']}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_seat_FL_SL63_black-leather_0'].geometry}
            material={materials['SL63_black-leather']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_seat_FL_SL63_darkred_0.geometry}
            material={materials.SL63_darkred}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_seat_FL_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_seat_FL_SL63_stitching_0.geometry}
            material={materials.SL63_stitching}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_seat_FL_SL63_white-leather_0'].geometry}
            material={materials['SL63_white-leather']}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_seat_FR_SL63_black-leather_0'].geometry}
            material={materials['SL63_black-leather']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_seat_FR_SL63_darkred_0.geometry}
            material={materials.SL63_darkred}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_seat_FR_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_seat_FR_SL63_stitching_0.geometry}
            material={materials.SL63_stitching}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_seat_FR_SL63_white-leather_0'].geometry}
            material={materials['SL63_white-leather']}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_shifter_A_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_shifter_A_SL63_interiorSymbs_0.geometry}
            material={materials.SL63_interiorSymbs}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_shiftlight-dash_shiftlight_multi_0'].geometry}
            material={materials.shiftlight_multi}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_shiftlight-dash_shiftlight_multi_l0_0'].geometry}
            material={materials.shiftlight_multi_l0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_shiftlight-dash_shiftlight_multi_l1_0'].geometry}
            material={materials.shiftlight_multi_l1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_shiftlight-dash_shiftlight_multi_l2_0'].geometry}
            material={materials.shiftlight_multi_l2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_shiftlight-dash_shiftlight_multi_l3_0'].geometry}
            material={materials.shiftlight_multi_l3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_shiftlight-dash_shiftlight_multi_l4_0'].geometry}
            material={materials.shiftlight_multi_l4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_shiftlight-dash_shiftlight_multi_l5_0'].geometry}
            material={materials.shiftlight_multi_l5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_shiftlight-dash_shiftlight_multi_l6_0'].geometry}
            material={materials.shiftlight_multi_l6}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_shiftlight-dash_shiftlight_multi_l7_0'].geometry}
            material={materials.shiftlight_multi_l7}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_sideskirt-L-crb_SL63_carbon_0'].geometry}
            material={materials.SL63_carbon}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_sideskirt-L-crb_SL63_paint_0'].geometry}
            material={materials.SL63_paint}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_sideskirt-R-crb_SL63_carbon_0'].geometry}
            material={materials.SL63_carbon}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_sideskirt-R-crb_SL63_paint_0'].geometry}
            material={materials.SL63_paint}
          />
        </group>
        <group position={[39.735, 75.215, 13.619]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_signalstalk_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_signalstalk_SL63_interiorSymbs_0.geometry}
            material={materials.SL63_interiorSymbs}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_spoiler-R_SL63_paint_0'].geometry}
            material={materials.SL63_paint}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_spoiler-R_SL63_silver_0'].geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group position={[34.686, 73.21, 9.586]} rotation={[-2.845, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_steeringwheel-crb_SL63_black-leather_0'].geometry}
            material={materials['SL63_black-leather']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_steeringwheel-crb_SL63_black_0'].geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_steeringwheel-crb_SL63_carbon_0'].geometry}
            material={materials.SL63_carbon}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_steeringwheel-crb_SL63_steerSymbs_0'].geometry}
            material={materials.SL63_steerSymbs}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_steeringwheel-crb_SL63_white-leather_0'].geometry}
            material={materials['SL63_white-leather']}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_taillight_L_SL63_beams-R_0'].geometry}
            material={materials['SL63_beams-R']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_L_SL63_brakelight_0.geometry}
            material={materials.SL63_brakelight}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_L_SL63_darkred_0.geometry}
            material={materials.SL63_darkred}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_L_SL63_plastic_0.geometry}
            material={materials.SL63_plastic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_L_SL63_reverselight_0.geometry}
            material={materials.SL63_reverselight}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_taillight_L_SL63_runninglight-R_0'].geometry}
            material={materials['SL63_runninglight-R']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_L_SL63_signal_L_6_0.geometry}
            material={materials.SL63_signal_L_6}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_L_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_taillight_R_SL63_beams-R_0'].geometry}
            material={materials['SL63_beams-R']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_brakelight_0.geometry}
            material={materials.SL63_brakelight}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_darkred_0.geometry}
            material={materials.SL63_darkred}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_plastic_0.geometry}
            material={materials.SL63_plastic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_reverselight_0.geometry}
            material={materials.SL63_reverselight}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SL63_taillight_R_SL63_runninglight-R_0'].geometry}
            material={materials['SL63_runninglight-R']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_signal_R_10_0.geometry}
            material={materials.SL63_signal_R_10}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_signal_R_11_0.geometry}
            material={materials.SL63_signal_R_11}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_signal_R_12_0.geometry}
            material={materials.SL63_signal_R_12}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_signal_R_13_0.geometry}
            material={materials.SL63_signal_R_13}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_signal_R_14_0.geometry}
            material={materials.SL63_signal_R_14}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_signal_R_15_0.geometry}
            material={materials.SL63_signal_R_15}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_signal_R_1_0.geometry}
            material={materials.SL63_signal_R_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_signal_R_2_0.geometry}
            material={materials.SL63_signal_R_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_signal_R_3_0.geometry}
            material={materials.SL63_signal_R_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_signal_R_4_0.geometry}
            material={materials.SL63_signal_R_4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_signal_R_5_0.geometry}
            material={materials.SL63_signal_R_5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_signal_R_6_0.geometry}
            material={materials.SL63_signal_R_6}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_signal_R_7_0.geometry}
            material={materials.SL63_signal_R_7}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_signal_R_8_0.geometry}
            material={materials.SL63_signal_R_8}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_signal_R_9_0.geometry}
            material={materials.SL63_signal_R_9}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_taillight_R_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_trunk_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_trunk_SL63_brakelight_0.geometry}
            material={materials.SL63_brakelight}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_trunk_SL63_paint_0.geometry}
            material={materials.SL63_paint}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_trunk_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_turbos_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_turbos_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group position={[77.659, 33.372, 118.575]} rotation={[-Math.PI / 2, 0, 0]} scale={106.168}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_wheel_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_wheel_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group
          position={[77.659, 33.372, -132.584]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={106.168}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_wheel001_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_wheel001_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group
          position={[-77.202, 33.372, 118.575]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={-106.168}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_wheel002_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_wheel002_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
        </group>
        <group
          position={[-77.202, 33.372, -132.584]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={-106.168}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_wheel003_SL63_black_0.geometry}
            material={materials.SL63_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SL63_wheel003_SL63_silver_0.geometry}
            material={materials.SL63_silver}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object_4001_Scene_-_Root002_0'].geometry}
          material={materials['Scene_-_Root.002']}
          position={[77.162, 33.372, -132.584]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[127.027, 104.296, 104.296]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object_4002_Scene_-_Root002_0'].geometry}
          material={materials['Scene_-_Root.002']}
          position={[-76.704, 33.372, 118.575]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[-127.027, -104.296, -104.296]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object_4003_Scene_-_Root002_0'].geometry}
          material={materials['Scene_-_Root.002']}
          position={[77.162, 33.372, 118.575]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[127.027, 104.296, 104.296]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object_4004_Scene_-_Root002_0'].geometry}
          material={materials['Scene_-_Root.002']}
          position={[-76.704, 33.372, -132.584]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[-127.027, -104.296, -104.296]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SL63_badge-F-AMG_body6_0'].geometry}
          material={materials['body.6']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_brakepedal_SL63_silver_0.geometry}
          material={materials['SL63_silver.001']}
          position={[38.678, 51.536, 50.232]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_bumperbar_F_SL63_radiatorsupp_0.geometry}
          material={materials.SL63_radiatorsupp}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_diff_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_diff_F_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SL63_doorglass_L-tint_SL63_tinted-glass_0'].geometry}
          material={materials['SL63_tinted-glass']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SL63_doorglass_R-tint_SL63_tinted-glass_0'].geometry}
          material={materials['SL63_tinted-glass']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_driveshaft_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          position={[-0.275, 30.789, -10.982]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[100, 105.129, 100]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_driveshaft_F_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          position={[12.826, 26.658, 73.686]}
          rotation={[Math.PI / 2, 1.453, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_exhaust_L_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_exhaust_R_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_fueltank_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_gaspedal_SL63_silver_0.geometry}
          material={materials['SL63_silver.001']}
          position={[25.178, 20.885, 41.09]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_halfshaft_F_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_halfshaft_R_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SL63_headlightglass_R-tint_SL63_tinted-glass001_0'].geometry}
          material={materials['SL63_tinted-glass.001']}
          position={[0, 0.1, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_heatshield_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_hub_F_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_hub_R_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_lettering_trunk_amg_SL63_silver_0.geometry}
          material={materials.SL63_silver}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_lettering_trunk_SL63_SL63_silver_0.geometry}
          material={materials.SL63_silver}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_logo_R_SL63_silver_0.geometry}
          material={materials.SL63_silver}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_lowerarm_F_a_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_lowerarm_F_b_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_lowerarm_R_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_muffler_L_bastion_mechanical_0.geometry}
          material={materials.bastion_mechanical}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_muffler_R_bastion_mechanical_0.geometry}
          material={materials.bastion_mechanical}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_radiator_SL63_radiatorsupp_0.geometry}
          material={materials.SL63_radiatorsupp}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_radsupport_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_shock_R_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_spring_R_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_steeringbox_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_strut_F_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[100, 100, 96.778]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_subframe_F_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_subframe_R_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SL63_sunvisor_SL63_black-leather_0'].geometry}
          material={materials['SL63_black-leather']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_swaybar_F_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_swaybar_R_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SL63_taillightglass_L-tint_SL63_tinted-glass_0'].geometry}
          material={materials['SL63_tinted-glass']}
          position={[0.111, -0.284, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SL63_taillightglass_R-tint_SL63_tinted-glass_0'].geometry}
          material={materials['SL63_tinted-glass']}
          position={[0.111, -0.284, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_tierod_F_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_tierod_R_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_transfercase_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_transmission_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SL63_tub-RL_bastion_mechanical_0'].geometry}
          material={materials.bastion_mechanical}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SL63_tub-RR_bastion_mechanical_0'].geometry}
          material={materials.bastion_mechanical}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_tubs_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_underbody_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_upperarm_R_SL63_underbody_0.geometry}
          material={materials.SL63_underbody}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SL63_windshield-tint_SL63_tinted-glass_0'].geometry}
          material={materials['SL63_tinted-glass']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SL63_wipers_SL63_black_0.geometry}
          material={materials.SL63_black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload('model/sl63.glb')