/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { useEffect } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Ford_ShelbyGT350R_2016_Wheel_1Combined3DWheel_3DWheel_front_L_I: THREE.Mesh
    Ford_ShelbyGT350R_2016CombinedCalliperBodyExotic6_Instance1_Src: THREE.Mesh
    Ford_ShelbyGT350R_2016Badge_Geo_lodA: THREE.Mesh
    Ford_ShelbyGT350R_2016Base_Geo_lodA: THREE.Mesh
    Ford_ShelbyGT350R_2016Carbon2M_Geo_lodA: THREE.Mesh
    Ford_ShelbyGT350R_2016Coloured_Geo_lodA: THREE.Mesh
    Ford_ShelbyGT350R_2016Engine_Geo_lodA: THREE.Mesh
    Ford_ShelbyGT350R_2016Grille2_Geo_lodA: THREE.Mesh
    Ford_ShelbyGT350R_2016Interior_Geo_lodA: THREE.Mesh
    Ford_ShelbyGT350R_2016Light_Geo_lodA: THREE.Mesh
    Ford_ShelbyGT350R_2016ManufacturerPlate_Geo_lodA: THREE.Mesh
    Ford_ShelbyGT350R_2016Paint_Geo_lodA: THREE.Mesh
    Ford_ShelbyGT350R_2016SeatBelt_Geo_lodA: THREE.Mesh
    Ford_ShelbyGT350R_2016Window_Geo_lodA: THREE.Mesh
    Ford_ShelbyGT350R_2016RearLights: THREE.Mesh
    Ford_ShelbyGT350R_2016Grille1_Geo_lodA: THREE.Mesh
    Ford_ShelbyGT350R_2016_Wheel_1Combined3DWheel_3DWheel_front: THREE.Mesh
    Ford_ShelbyGT350R_2016CombinedCalliperBodyExotic6_Instance1: THREE.Mesh
    Ford_ShelbyGT350R_2016_Wheel_1Combined3DWheel_3DWheel_front001: THREE.Mesh
    Ford_ShelbyGT350R_2016CombinedCalliperBodyExotic6_Instance1001: THREE.Mesh
    Ford_ShelbyGT350R_2016_Wheel_1Combined3DWheel_3DWheel_front002: THREE.Mesh
    Ford_ShelbyGT350R_2016CombinedCalliperBodyExotic6_Instance1002: THREE.Mesh
  }
  materials: {
    Wheel: THREE.MeshPhysicalMaterial
    Caliper: THREE.MeshPhysicalMaterial
    Badge: THREE.MeshPhysicalMaterial
    Base: THREE.MeshPhysicalMaterial
    Paint2: THREE.MeshPhysicalMaterial
    Engine: THREE.MeshStandardMaterial
    Grille02: THREE.MeshStandardMaterial
    Interior: THREE.MeshStandardMaterial
    Lights: THREE.MeshStandardMaterial
    Plate: THREE.MeshPhysicalMaterial
    Paint: THREE.MeshPhysicalMaterial
    Seatbelt: THREE.MeshStandardMaterial
    Glass: THREE.MeshPhysicalMaterial
    RearLights: THREE.MeshPhysicalMaterial
    Grille01: THREE.MeshStandardMaterial
    ['Wheel.002']: THREE.MeshPhysicalMaterial
    ['Caliper.002']: THREE.MeshPhysicalMaterial
    ['Wheel.003']: THREE.MeshPhysicalMaterial
    ['Caliper.003']: THREE.MeshPhysicalMaterial
  }
}

export function GT350R(props: any) {
  const { nodes, materials } = useGLTF('models/gt350r.glb') as GLTFResult

  useEffect(() => {
    // car paint
    Object.entries(materials).map((material) => {
      if (material[0] == "Paint") {
        material[1].color = new THREE.Color(props.color.hexCode);
      }
      material[1].needsUpdate = true;
    });
  }, [materials, props]);

  return (
    <group {...props} dispose={null} scale={4} position={[0, -1.52, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ford_ShelbyGT350R_2016_Wheel_1Combined3DWheel_3DWheel_front_L_I.geometry}
        material={materials.Wheel}
        position={[-0.794, 0.18, -1.288]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ford_ShelbyGT350R_2016CombinedCalliperBodyExotic6_Instance1_Src.geometry}
          material={materials.Caliper}
          position={[0.008, -0.159, -0.056]}
          rotation={[Math.PI / 9, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ford_ShelbyGT350R_2016Badge_Geo_lodA.geometry}
        material={materials.Badge}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ford_ShelbyGT350R_2016Base_Geo_lodA.geometry}
        material={materials.Base}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ford_ShelbyGT350R_2016Carbon2M_Geo_lodA.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ford_ShelbyGT350R_2016Coloured_Geo_lodA.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ford_ShelbyGT350R_2016Engine_Geo_lodA.geometry}
        material={materials.Engine}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ford_ShelbyGT350R_2016Grille2_Geo_lodA.geometry}
        material={materials.Grille02}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ford_ShelbyGT350R_2016Interior_Geo_lodA.geometry}
        material={materials.Interior}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ford_ShelbyGT350R_2016Light_Geo_lodA.geometry}
        material={materials.Lights}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ford_ShelbyGT350R_2016ManufacturerPlate_Geo_lodA.geometry}
        material={materials.Plate}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ford_ShelbyGT350R_2016Paint_Geo_lodA.geometry}
        material={materials.Paint}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ford_ShelbyGT350R_2016SeatBelt_Geo_lodA.geometry}
        material={materials.Seatbelt}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ford_ShelbyGT350R_2016Window_Geo_lodA.geometry}
        material={materials.Glass}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ford_ShelbyGT350R_2016RearLights.geometry}
        material={materials.RearLights}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ford_ShelbyGT350R_2016Grille1_Geo_lodA.geometry}
        material={materials.Grille01}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ford_ShelbyGT350R_2016_Wheel_1Combined3DWheel_3DWheel_front.geometry}
        material={materials.Wheel}
        position={[-0.821, 0.18, 1.431]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.85, -1, -1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ford_ShelbyGT350R_2016CombinedCalliperBodyExotic6_Instance1.geometry}
          material={materials.Caliper}
          position={[0.008, -0.159, 0]}
          scale={[1.176, 1, 1]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ford_ShelbyGT350R_2016_Wheel_1Combined3DWheel_3DWheel_front001.geometry}
        material={materials['Wheel.002']}
        position={[0.821, 0.18, 1.431]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.85, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ford_ShelbyGT350R_2016CombinedCalliperBodyExotic6_Instance1001.geometry}
          material={materials['Caliper.002']}
          position={[0.008, -0.159, 0]}
          scale={[1.176, 1, 1]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ford_ShelbyGT350R_2016_Wheel_1Combined3DWheel_3DWheel_front002.geometry}
        material={materials['Wheel.003']}
        position={[0.794, 0.18, -1.288]}
        rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ford_ShelbyGT350R_2016CombinedCalliperBodyExotic6_Instance1002.geometry}
          material={materials['Caliper.003']}
          position={[0.008, -0.159, -0.056]}
          rotation={[Math.PI / 9, 0, 0]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('models/gt350r.glb')
