/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Black Snow (https://sketchfab.com/BlackSnow02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ferrari-f40-52a66c41cfcd4f999fb1b1c49bf24d70
Title: Ferrari f40
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_35: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_39: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_41: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_43: THREE.Mesh;
  };
  materials: {
    F40_Carbon: THREE.MeshStandardMaterial;
    F40_GridD: THREE.MeshStandardMaterial;
    F40_Headlights: THREE.MeshStandardMaterial;
    F40_Sheft: THREE.MeshStandardMaterial;
    ["F40_Window.001"]: THREE.MeshStandardMaterial;
    super_brakelight: THREE.MeshStandardMaterial;
    super_reverselight: THREE.MeshStandardMaterial;
    material: THREE.MeshPhysicalMaterial;
    F40_Brake: THREE.MeshStandardMaterial;
    F40_Chrome: THREE.MeshStandardMaterial;
    ["F40_Chrome.001"]: THREE.MeshStandardMaterial;
    F40_Cockpit: THREE.MeshStandardMaterial;
    F40_Cockpit_HR: THREE.MeshStandardMaterial;
    F40_Display: THREE.MeshStandardMaterial;
    F40_Display_1: THREE.MeshStandardMaterial;
    F40_Estra: THREE.MeshStandardMaterial;
    F40_Glass: THREE.MeshStandardMaterial;
    ["F40_Glass.001"]: THREE.MeshStandardMaterial;
    F40_Grid: THREE.MeshStandardMaterial;
    F40_Logos: THREE.MeshStandardMaterial;
    F40_Mechanics: THREE.MeshStandardMaterial;
    ["F40_Mechanics.001"]: THREE.MeshStandardMaterial;
    F40_Pedali: THREE.MeshStandardMaterial;
    F40_Rrims: THREE.MeshStandardMaterial;
    F40_Skin: THREE.MeshStandardMaterial;
    F40_Strelki: THREE.MeshStandardMaterial;
    F40_Tappetini: THREE.MeshStandardMaterial;
    F40_Vehiclelight: THREE.MeshStandardMaterial;
    F40_Window: THREE.MeshStandardMaterial;
    ["Scene_-_Root.002"]: THREE.MeshStandardMaterial;
    super_gauges: THREE.MeshStandardMaterial;
    super_headlight: THREE.MeshStandardMaterial;
    super_signal_L: THREE.MeshStandardMaterial;
  };
};

export function F40(props: any) {
  const { nodes, materials } = useGLTF("model/ferrari_f40.glb") as GLTFResult;
  const carModel = useRef<THREE.Group<THREE.Object3DEventMap>>(null);

  useEffect(() => {
    // enable car shadows
    carModel.current?.traverse((child) => {
      if (child instanceof THREE.Mesh) {
        child.castShadow = true;
        child.receiveShadow = true;
      }
    });

    // car paint
    Object.entries(materials).map((material) => {
      if (material[0] == "material") {
        material[1].color = new THREE.Color(props.color.hexCode);
      } 
      if (material[0] == "F40_Rrims" || material[0] == "F40_Carbon") {
        material[1].color = new THREE.Color("#fff");
      }
      material[1].needsUpdate = true;
    });
  }, [materials, props]);

  return (
    <group {...props} dispose={null} ref={carModel} scale={4}>
      <group rotation={[-Math.PI / 2, 0, -1.12]} position={[0, -0.3, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.F40_Carbon}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.F40_GridD}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.F40_Headlights}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.F40_Sheft}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials["F40_Window.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.super_brakelight}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.super_reverselight}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.F40_Brake}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.F40_Chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.F40_Chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials["F40_Chrome.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials.F40_Cockpit}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials.F40_Cockpit}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials.F40_Cockpit}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials.F40_Cockpit_HR}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={materials.F40_Display}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_20.geometry}
          material={materials.F40_Display_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials.F40_Estra}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials.F40_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials["F40_Glass.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_24.geometry}
          material={materials.F40_Grid}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_25.geometry}
          material={materials.F40_Logos}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_26.geometry}
          material={materials.F40_Mechanics}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_27.geometry}
          material={materials.F40_Mechanics}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_28.geometry}
          material={materials["F40_Mechanics.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_29.geometry}
          material={materials.F40_Pedali}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_30.geometry}
          material={materials.F40_Rrims}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_31.geometry}
          material={materials.F40_Rrims}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_32.geometry}
          material={materials.F40_Skin}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_33.geometry}
          material={materials.F40_Strelki}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_34.geometry}
          material={materials.F40_Tappetini}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_35.geometry}
          material={materials.F40_Vehiclelight}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_36.geometry}
          material={materials.F40_Window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_37.geometry}
          material={materials["Scene_-_Root.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_38.geometry}
          material={materials["Scene_-_Root.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_39.geometry}
          material={materials["Scene_-_Root.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_40.geometry}
          material={materials["Scene_-_Root.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_41.geometry}
          material={materials.super_gauges}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_42.geometry}
          material={materials.super_headlight}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_43.geometry}
          material={materials.super_signal_L}
        />
      </group>
    </group>
  );
}

useGLTF.preload("model/ferrari_f40.glb");
