/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: WARENTERTAINMENT™ (https://sketchfab.com/WarEntertainment)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lamborghini-huracan-basic-edition-f4004ef10bd44845b3cece359e6a6b2e
Title: Lamborghini Huracan (Basic Edition)
*/

import * as THREE from "three";
import { useGLTF } from '@react-three/drei'

export function CarModel(props: any) {
  const { nodes, materials } = useGLTF('/model/lamborghini_huracan_basic_edition.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_6 as THREE.Mesh).geometry}
          material={materials.Brake2Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_8 as THREE.Mesh).geometry}
          material={materials.LicensePlate2Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_10 as THREE.Mesh).geometry}
          material={materials.Meshpart11Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_12 as THREE.Mesh).geometry}
          material={materials.Meshpart27Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_14 as THREE.Mesh).geometry}
          material={materials.Meshpart30Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_16 as THREE.Mesh).geometry}
          material={materials.Steering2Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_18 as THREE.Mesh).geometry}
          material={materials.Details1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_20 as THREE.Mesh).geometry}
          material={materials.Disc1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_22 as THREE.Mesh).geometry}
          material={materials.Hb1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_24 as THREE.Mesh).geometry}
          material={materials.LicensePlate1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_26 as THREE.Mesh).geometry}
          material={materials.LicensePlate1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_28 as THREE.Mesh).geometry}
          material={materials.LicensePlate1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_30 as THREE.Mesh).geometry}
          material={materials.LicensePlate1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_32 as THREE.Mesh).geometry}
          material={materials.LicensePlate1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_34 as THREE.Mesh).geometry}
          material={materials.LicensePlate1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_36 as THREE.Mesh).geometry}
          material={materials.Meshpart14Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_38 as THREE.Mesh).geometry}
          material={materials.Meshpart18Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_40 as THREE.Mesh).geometry}
          material={materials.Meshpart5Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_42 as THREE.Mesh).geometry}
          material={materials.Mirrorreflections1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_44 as THREE.Mesh).geometry}
          material={materials.Mirrorreflections1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_46 as THREE.Mesh).geometry}
          material={materials.Mirrorreflections1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_48 as THREE.Mesh).geometry}
          material={materials.Mirrorreflections1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_50 as THREE.Mesh).geometry}
          material={materials.Mirrorreflections1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_52 as THREE.Mesh).geometry}
          material={materials.Mirrorreflections1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_54 as THREE.Mesh).geometry}
          material={materials.Mirrorreflections1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_56 as THREE.Mesh).geometry}
          material={materials.Paint1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_58 as THREE.Mesh).geometry}
          material={materials.Paint1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_60 as THREE.Mesh).geometry}
          material={materials.Rright1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_62 as THREE.Mesh).geometry}
          material={materials.Runl1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_64 as THREE.Mesh).geometry}
          material={materials.Threads1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_66 as THREE.Mesh).geometry}
          material={materials.Tire1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_68 as THREE.Mesh).geometry}
          material={materials.Wipers1Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_70 as THREE.Mesh).geometry}
          material={materials.Wipers1Mtl}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/model/lamborghini_huracan_basic_edition.glb')