/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_2: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
  };
  materials: {
    headlight_glass: THREE.MeshPhysicalMaterial;
    headlight_plastic: THREE.MeshStandardMaterial;
    headlight_led: THREE.MeshStandardMaterial;
    interior: THREE.MeshPhysicalMaterial;
    plastic: THREE.MeshStandardMaterial;
    mirror: THREE.MeshStandardMaterial;
    taillight_glass: THREE.MeshPhysicalMaterial;
    taillight: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    brake_disc: THREE.MeshPhysicalMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    brake_disc1: THREE.MeshPhysicalMaterial;
    blinker_glass: THREE.MeshPhysicalMaterial;
    ["Material.003"]: THREE.MeshPhysicalMaterial;
    headlight_chrome: THREE.MeshStandardMaterial;
    logo: THREE.MeshStandardMaterial;
    ["nothing."]: THREE.MeshPhysicalMaterial;
    ["rubber.001"]: THREE.MeshPhysicalMaterial;
    ["wheel_metal.002"]: THREE.MeshPhysicalMaterial;
    ["Material.006"]: THREE.MeshPhysicalMaterial;
    ["Material.001"]: THREE.MeshPhysicalMaterial;
    material: THREE.MeshPhysicalMaterial;
    ["Material.008"]: THREE.MeshPhysicalMaterial;
    ["Material.029"]: THREE.MeshPhysicalMaterial;
    ["Material.002"]: THREE.MeshPhysicalMaterial;
    headlight_lens: THREE.MeshStandardMaterial;
  };
};

export function E46M3(props: any) {
  const { nodes, materials } = useGLTF("model/m3_e46.glb") as GLTFResult;
  const carModel = useRef<THREE.Group<THREE.Object3DEventMap>>(null);

  useEffect(() => {
    // enable car shadows
    carModel.current?.traverse((child) => {
      if (child instanceof THREE.Mesh) {
        child.castShadow = true;
        child.receiveShadow = true;
      }
    });

    // car paint
    Object.entries(materials).map((material) => {
      if (material[0] == "Material.003") {
        material[1].color = new THREE.Color(props.color.hexCode);
      }
      material[1].needsUpdate = true;
    });
  }, [materials, props]);

  return (
    <group
      {...props}
      dispose={null}
      ref={carModel}
      rotation={[0, -1.1, 0]}
      scale={3}
      position={[0, -1.75, 0]}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.headlight_glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.headlight_plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.headlight_led}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.interior}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials.mirror}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials.taillight_glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials.taillight}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={materials.brake_disc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_20.geometry}
          material={materials.brake_disc1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials.blinker_glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials.headlight_chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_24.geometry}
          material={materials.logo}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_25.geometry}
          material={materials["nothing."]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_26.geometry}
          material={materials["rubber.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_27.geometry}
          material={materials["wheel_metal.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_28.geometry}
          material={materials["wheel_metal.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials["Material.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.headlight_lens}
        />
      </group>
    </group>
  );
}

useGLTF.preload("model/m3_e46.glb");
