/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Ferrari_F12berlinetta_2014_Wheel_1ACombined3DWheel_3DWheel_002: THREE.Mesh
    Ferrari_F12berlinetta_2014_Wheel_1ACombined3DWheel_3DWheel_fron: THREE.Mesh
    Ferrari_F12berlinetta_2014CombinedCalliperBodyExotic6_Instance1: THREE.Mesh
    Ferrari_F12berlinetta_2014Base_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Engine_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Grille1_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Grille2_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Kit0_Badge_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Kit0_Carbon2_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Kit0_Coloured_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Kit0_Interior_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Kit0_Paint_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Light_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014ManufacturerPlate_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014SeatBelt_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Window_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014_Wheel_1ACombined3DWheel_3DWheel_: THREE.Mesh
    Ferrari_F12berlinetta_2014CombinedCalliperBodyExotic6_Insta: THREE.Mesh
    Ferrari_F12berlinetta_2014_Wheel_1ACombined3DWheel_3DWheel_001: THREE.Mesh
    Ferrari_F12berlinetta_2014CombinedCalliperBodyExotic6_Insta001: THREE.Mesh
  }
  materials: {
    ['Wheel.003']: THREE.MeshPhysicalMaterial
    Wheel: THREE.MeshPhysicalMaterial
    Caliper: THREE.MeshStandardMaterial
    Paint2: THREE.MeshStandardMaterial
    Engine: THREE.MeshStandardMaterial
    Grille1: THREE.MeshStandardMaterial
    Grille2: THREE.MeshStandardMaterial
    Badge: THREE.MeshStandardMaterial
    Interior: THREE.MeshStandardMaterial
    BodyPaint: THREE.MeshStandardMaterial
    Lights: THREE.MeshStandardMaterial
    Plate: THREE.MeshStandardMaterial
    Seatbelt: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['Caliper.001']: THREE.MeshStandardMaterial
    ['Caliper.002']: THREE.MeshStandardMaterial
  }
}

export function F12(props: any) {
  const { nodes, materials } = useGLTF('model/f12.glb') as GLTFResult

  useEffect(() => {
    // car paint
    Object.entries(materials).map((material) => {
      if (material[0] == "BodyPaint") {
        material[1].color = new THREE.Color(props.color.hexCode);
      }
      material[1].needsUpdate = true;
    });
  }, [materials, props]);


  return (
    <group {...props} dispose={null} scale={4} position={[0, -1.05, 0]} rotation={[0,-1,0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014_Wheel_1ACombined3DWheel_3DWheel_002.geometry}
        material={materials['Wheel.003']}
        position={[0.785, 0.229, -1.358]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014_Wheel_1ACombined3DWheel_3DWheel_fron.geometry}
        material={materials.Wheel}
        position={[-0.785, 0.229, -1.358]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ferrari_F12berlinetta_2014CombinedCalliperBodyExotic6_Instance1.geometry}
          material={materials.Caliper}
          position={[0.005, 0.169, 0]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={-1}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Base_Geo_lodA.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Engine_Geo_lodA.geometry}
        material={materials.Engine}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Grille1_Geo_lodA.geometry}
        material={materials.Grille1}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Grille2_Geo_lodA.geometry}
        material={materials.Grille2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Kit0_Badge_Geo_lodA.geometry}
        material={materials.Badge}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Kit0_Carbon2_Geo_lodA.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Kit0_Coloured_Geo_lodA.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Kit0_Interior_Geo_lodA.geometry}
        material={materials.Interior}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Kit0_Paint_Geo_lodA.geometry}
        material={materials.BodyPaint}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Light_Geo_lodA.geometry}
        material={materials.Lights}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014ManufacturerPlate_Geo_lodA.geometry}
        material={materials.Plate}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014SeatBelt_Geo_lodA.geometry}
        material={materials.Seatbelt}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Window_Geo_lodA.geometry}
        material={materials.Glass}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014_Wheel_1ACombined3DWheel_3DWheel_.geometry}
        material={materials.Wheel}
        position={[0.785, 0.229, 1.357]}
        rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ferrari_F12berlinetta_2014CombinedCalliperBodyExotic6_Insta.geometry}
          material={materials['Caliper.001']}
          position={[0.005, -0.169, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014_Wheel_1ACombined3DWheel_3DWheel_001.geometry}
        material={materials.Wheel}
        position={[-0.785, 0.229, 1.357]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ferrari_F12berlinetta_2014CombinedCalliperBodyExotic6_Insta001.geometry}
          material={materials['Caliper.002']}
          position={[0.005, -0.169, 0]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('model/f12.glb')