/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Ferrari_F12berlinetta_2014_Wheel_1Combined3DWheel_3DWheel_f: THREE.Mesh
    Ferrari_F12berlinetta_2014CombinedCalliperBodyExotic6_Insta004: THREE.Mesh
    Ferrari_F12berlinetta_2014Base_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Engine_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Grille1_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Grille2_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Kit0_Badge_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Kit0_Carbon2_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Kit0_Coloured_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Kit0_Interior_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Kit0_Paint_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Light_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014ManufacturerPlate_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014SeatBelt_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014Window_Geo_lodA: THREE.Mesh
    Ferrari_F12berlinetta_2014RearEmissions: THREE.Mesh
    Ferrari_F12berlinetta_2014_Wheel_1Combined3DWheel_3DWheel_front: THREE.Mesh
    Ferrari_F12berlinetta_2014CombinedCalliperBodyExotic6_Insta001: THREE.Mesh
    Ferrari_F12berlinetta_2014_Wheel_1Combined3DWheel_3DWheel_f001: THREE.Mesh
    Ferrari_F12berlinetta_2014CombinedCalliperBodyExotic6_Insta003: THREE.Mesh
    Ferrari_F12berlinetta_2014_Wheel_1Combined3DWheel_3DWheel_f002: THREE.Mesh
    Ferrari_F12berlinetta_2014CombinedCalliperBodyExotic6_Insta002: THREE.Mesh
  }
  materials: {
    Wheel: THREE.MeshPhysicalMaterial
    ['Caliper.011']: THREE.MeshStandardMaterial
    Paint2: THREE.MeshStandardMaterial
    Engine: THREE.MeshStandardMaterial
    Grille1: THREE.MeshStandardMaterial
    Grille2: THREE.MeshStandardMaterial
    Badge: THREE.MeshStandardMaterial
    Interior: THREE.MeshStandardMaterial
    BodyPaint: THREE.MeshStandardMaterial
    Lights: THREE.MeshStandardMaterial
    Plate: THREE.MeshStandardMaterial
    Seatbelt: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    RearEmission: THREE.MeshStandardMaterial
    ['Caliper.003']: THREE.MeshStandardMaterial
    ['Caliper.006']: THREE.MeshStandardMaterial
    ['Caliper.010']: THREE.MeshStandardMaterial
  }
}


export function F12(props: any) {
  const { nodes, materials } = useGLTF('model/f12.glb') as GLTFResult

  useEffect(() => {
    // car paint
    Object.entries(materials).map((material) => {
      if (material[0] == "BodyPaint") {
        material[1].color = new THREE.Color(props.color.hexCode);
      }
      material[1].needsUpdate = true;
    });
  }, [materials, props]);


  return (
    <group {...props} dispose={null} scale={4} position={[0, -1.66, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014_Wheel_1Combined3DWheel_3DWheel_f.geometry}
        material={materials.Wheel}
        position={[-0.777, 0.224, -1.363]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ferrari_F12berlinetta_2014CombinedCalliperBodyExotic6_Insta004.geometry}
          material={materials['Caliper.011']}
          position={[0.007, 0.155, 0]}
          rotation={[-Math.PI, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Base_Geo_lodA.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Engine_Geo_lodA.geometry}
        material={materials.Engine}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Grille1_Geo_lodA.geometry}
        material={materials.Grille1}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Grille2_Geo_lodA.geometry}
        material={materials.Grille2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Kit0_Badge_Geo_lodA.geometry}
        material={materials.Badge}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Kit0_Carbon2_Geo_lodA.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Kit0_Coloured_Geo_lodA.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Kit0_Interior_Geo_lodA.geometry}
        material={materials.Interior}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Kit0_Paint_Geo_lodA.geometry}
        material={materials.BodyPaint}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Light_Geo_lodA.geometry}
        material={materials.Lights}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014ManufacturerPlate_Geo_lodA.geometry}
        material={materials.Plate}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014SeatBelt_Geo_lodA.geometry}
        material={materials.Seatbelt}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014Window_Geo_lodA.geometry}
        material={materials.Glass}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014RearEmissions.geometry}
        material={materials.RearEmission}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014_Wheel_1Combined3DWheel_3DWheel_front.geometry}
        material={materials.Wheel}
        position={[0.777, 0.224, -1.363]}
        rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ferrari_F12berlinetta_2014CombinedCalliperBodyExotic6_Insta001.geometry}
          material={materials['Caliper.003']}
          position={[0.007, 0.155, 0]}
          rotation={[-Math.PI, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014_Wheel_1Combined3DWheel_3DWheel_f001.geometry}
        material={materials.Wheel}
        position={[-0.777, 0.224, 1.354]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ferrari_F12berlinetta_2014CombinedCalliperBodyExotic6_Insta003.geometry}
          material={materials['Caliper.006']}
          position={[0, -0.167, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ferrari_F12berlinetta_2014_Wheel_1Combined3DWheel_3DWheel_f002.geometry}
        material={materials.Wheel}
        position={[0.777, 0.224, 1.354]}
        rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ferrari_F12berlinetta_2014CombinedCalliperBodyExotic6_Insta002.geometry}
          material={materials['Caliper.010']}
          position={[0, -0.167, 0]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('model/f12.glb')
