/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useEffect } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Nissan_GTR_2017_CallipersCombinedCalliperExotic6CalliperExotic6: THREE.Mesh;
    Nissan_GTR_2017_Wheel_2Combined3DWheel_3DWheel_front_L_Instance: THREE.Mesh;
    Nissan_GTR_2017Engine_Geo_lodA: THREE.Mesh;
    Nissan_GTR_2017Kit1_Base_Geo_lodA: THREE.Mesh;
    Nissan_GTR_2017Kit1_Carbon1_Geo_lodA: THREE.Mesh;
    Nissan_GTR_2017Kit1_Coloured_Geo_lodA: THREE.Mesh;
    Nissan_GTR_2017Kit1_Grille1_Geo_lodA: THREE.Mesh;
    Nissan_GTR_2017Kit1_Grille2_Geo_lodA: THREE.Mesh;
    Nissan_GTR_2017Kit1_Grille3_Geo_lodA: THREE.Mesh;
    Nissan_GTR_2017Kit1_Grille4_Geo_lodA: THREE.Mesh;
    Nissan_GTR_2017Kit1_Interior_Geo_lodA: THREE.Mesh;
    Nissan_GTR_2017Kit1_InteriorTillingColourZone_Geo_lodA: THREE.Mesh;
    Nissan_GTR_2017Kit1_Light_Geo_lodA_1: THREE.Mesh;
    Nissan_GTR_2017Kit1_Light_Geo_lodA_2: THREE.Mesh;
    Nissan_GTR_2017Kit1_Paint_Geo_lodA: THREE.Mesh;
    Nissan_GTR_2017Kit1_SeatBelt_Geo_lodA: THREE.Mesh;
    Nissan_GTR_2017Kit1_Window_Geo_lodA: THREE.Mesh;
    Nissan_GTR_2017ManufacturerPlate_Geo_lodA: THREE.Mesh;
    Nissan_GTR_2017Kit1_RearLights: THREE.Mesh;
    Nissan_GTR_2017Kit1_Badge_Geo_lodA: THREE.Mesh;
    Nissan_GTR_2017_Wheel_2Combined3DWheel_3DWheel_front_L_Inst: THREE.Mesh;
    Nissan_GTR_2017_CallipersCombinedCalliperExotic6CalliperExo: THREE.Mesh;
    Nissan_GTR_2017_Wheel_2Combined3DWheel_3DWheel_front_L_Inst001: THREE.Mesh;
    Nissan_GTR_2017_CallipersCombinedCalliperExotic6CalliperExo001: THREE.Mesh;
    Nissan_GTR_2017_Wheel_2Combined3DWheel_3DWheel_front_L_Inst002: THREE.Mesh;
    Nissan_GTR_2017_CallipersCombinedCalliperExotic6CalliperExo002: THREE.Mesh;
  };
  materials: {
    Caliper: THREE.MeshStandardMaterial;
    Wheels: THREE.MeshPhysicalMaterial;
    Engine: THREE.MeshStandardMaterial;
    Base: THREE.MeshStandardMaterial;
    CarbonFiber: THREE.MeshPhysicalMaterial;
    Paint2: THREE.MeshPhysicalMaterial;
    Grille1: THREE.MeshStandardMaterial;
    Grille2: THREE.MeshStandardMaterial;
    Grille3: THREE.MeshStandardMaterial;
    Grille4: THREE.MeshStandardMaterial;
    Interior: THREE.MeshStandardMaterial;
    Interior2: THREE.MeshStandardMaterial;
    Lights: THREE.MeshStandardMaterial;
    Glass: THREE.MeshPhysicalMaterial;
    Paint: THREE.MeshPhysicalMaterial;
    Plate: THREE.MeshPhysicalMaterial;
    RearLights: THREE.MeshPhysicalMaterial;
    Badge: THREE.MeshPhysicalMaterial;
  };
};

export function GTR(props: any) {
  const { nodes, materials } = useGLTF("models/gtr_17.glb") as GLTFResult;

  useEffect(() => {
    // car paint
    Object.entries(materials).map((material) => {
      if (material[0] == "Paint") {
        material[1].color = new THREE.Color(props.color.hexCode);
      }
      material[1].needsUpdate = true;
    });
  }, [materials, props]);

  return (
    <group {...props} dispose={null} scale={4} position={[0, -2.23, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Nissan_GTR_2017_CallipersCombinedCalliperExotic6CalliperExotic6
            .geometry
        }
        material={materials.Caliper}
        position={[0.795, 0.358, 1.421]}
        rotation={[1.518, 0, 0]}
        scale={[0.85, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Nissan_GTR_2017_Wheel_2Combined3DWheel_3DWheel_front_L_Instance
            .geometry
        }
        material={materials.Wheels}
        position={[0.8, 0.358, 1.421]}
        rotation={[0.576, 0, 0]}
        scale={[0.85, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nissan_GTR_2017Engine_Geo_lodA.geometry}
        material={materials.Engine}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nissan_GTR_2017Kit1_Base_Geo_lodA.geometry}
        material={materials.Base}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nissan_GTR_2017Kit1_Carbon1_Geo_lodA.geometry}
        material={materials.CarbonFiber}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nissan_GTR_2017Kit1_Coloured_Geo_lodA.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nissan_GTR_2017Kit1_Grille1_Geo_lodA.geometry}
        material={materials.Grille1}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nissan_GTR_2017Kit1_Grille2_Geo_lodA.geometry}
        material={materials.Grille2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nissan_GTR_2017Kit1_Grille3_Geo_lodA.geometry}
        material={materials.Grille3}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nissan_GTR_2017Kit1_Grille4_Geo_lodA.geometry}
        material={materials.Grille4}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nissan_GTR_2017Kit1_Interior_Geo_lodA.geometry}
        material={materials.Interior}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Nissan_GTR_2017Kit1_InteriorTillingColourZone_Geo_lodA.geometry
        }
        material={materials.Interior2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Nissan_GTR_2017Kit1_Light_Geo_lodA_1.geometry}
          material={materials.Lights}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Nissan_GTR_2017Kit1_Light_Geo_lodA_2.geometry}
          material={materials.Glass}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nissan_GTR_2017Kit1_Paint_Geo_lodA.geometry}
        material={materials.Paint}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nissan_GTR_2017Kit1_SeatBelt_Geo_lodA.geometry}
        material={nodes.Nissan_GTR_2017Kit1_SeatBelt_Geo_lodA.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nissan_GTR_2017Kit1_Window_Geo_lodA.geometry}
        material={materials.Glass}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nissan_GTR_2017ManufacturerPlate_Geo_lodA.geometry}
        material={materials.Plate}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nissan_GTR_2017Kit1_RearLights.geometry}
        material={materials.RearLights}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nissan_GTR_2017Kit1_Badge_Geo_lodA.geometry}
        material={materials.Badge}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Nissan_GTR_2017_Wheel_2Combined3DWheel_3DWheel_front_L_Inst
            .geometry
        }
        material={materials.Wheels}
        position={[0.78, 0.358, -1.347]}
        rotation={[2.059, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Nissan_GTR_2017_CallipersCombinedCalliperExotic6CalliperExo
            .geometry
        }
        material={materials.Caliper}
        position={[0.774, 0.358, -1.347]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Nissan_GTR_2017_Wheel_2Combined3DWheel_3DWheel_front_L_Inst001
            .geometry
        }
        material={materials.Wheels}
        position={[-0.8, 0.358, 1.421]}
        rotation={[-1.082, 0, 0]}
        scale={[-0.85, -1, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Nissan_GTR_2017_CallipersCombinedCalliperExotic6CalliperExo001
            .geometry
        }
        material={materials.Caliper}
        position={[-0.795, 0.358, 1.421]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.85, -1, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Nissan_GTR_2017_Wheel_2Combined3DWheel_3DWheel_front_L_Inst002
            .geometry
        }
        material={materials.Wheels}
        position={[-0.78, 0.358, -1.347]}
        rotation={[2.007, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Nissan_GTR_2017_CallipersCombinedCalliperExotic6CalliperExo002
            .geometry
        }
        material={materials.Caliper}
        position={[-0.774, 0.358, -1.347]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={-1}
      />
    </group>
  );
}

useGLTF.preload("models/gtr_17.glb");
