/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Lamborghini_AventadorLP7504Superveloce_2015_Wheel_1ACombined3DW: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015CombinedCalliperBody: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015Parking: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015Badge_Geo_lodA: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015Base_Geo_lodA: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015Carbon1M_Geo_lodA: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015Coloured_Geo_lodA: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015Engine_Geo_lodA: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015Grille1_Geo_lodA: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015Grille2_Geo_lodA: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015Grille3_Geo_lodA: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015Grille4_Geo_lodA: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015Interior_Geo_lodA: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015Light_Geo_lodA: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015ManufacturerPlate_Ge: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015Paint_Geo_lodA: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015SeatBelt_Geo_lodA: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015Window_Geo_lodA: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015_Wheel_1ACombine: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015CombinedCalliper: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015_Wheel_1ACombine001: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015CombinedCalliper001: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015_Wheel_1ACombine002: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015CombinedCalliper002: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015Parking001: THREE.Mesh
    Lamborghini_AventadorLP7504Superveloce_2015RearLights: THREE.Mesh
  }
  materials: {
    Wheel: THREE.MeshPhysicalMaterial
    BodyPaint: THREE.MeshPhysicalMaterial
    ParkingBrake: THREE.MeshStandardMaterial
    Badge: THREE.MeshStandardMaterial
    Base: THREE.MeshStandardMaterial
    ExteriorPaint2: THREE.MeshStandardMaterial
    ExteriorPaint3: THREE.MeshStandardMaterial
    Engine: THREE.MeshStandardMaterial
    Grille1: THREE.MeshStandardMaterial
    Grille2: THREE.MeshStandardMaterial
    Grille3: THREE.MeshStandardMaterial
    Grille4: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    Lights: THREE.MeshStandardMaterial
    Plate: THREE.MeshStandardMaterial
    Seatbelt: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['BodyPaint.001']: THREE.MeshPhysicalMaterial
    ['BodyPaint.002']: THREE.MeshPhysicalMaterial
    ['BodyPaint.003']: THREE.MeshPhysicalMaterial
    ['ParkingBrake.001']: THREE.MeshStandardMaterial
    RearLights: THREE.MeshStandardMaterial
  }
}

export function AventadorSV(props: any) {
  const { nodes, materials } = useGLTF('model/aventador_sv.glb') as GLTFResult

  useEffect(() => {
    // car paint
    Object.entries(materials).map((material) => {
      if (material[0] == "BodyPaint") {
        material[1].color = new THREE.Color(props.color.hexCode);
      }
      material[1].needsUpdate = true;
    });
  }, [materials, props]);

  return (
    <group {...props} dispose={null} scale={4} position={[0, -1.09, 0]} rotation={[0,-1,0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015_Wheel_1ACombined3DW.geometry}
        material={materials.Wheel}
        position={[0.81, 0.201, -1.44]}
        rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015CombinedCalliperBody.geometry}
          material={materials.BodyPaint}
          position={[0.002, 0.161, -0.062]}
          rotation={[2.793, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015Parking.geometry}
          material={materials.ParkingBrake}
          position={[0.009, -0.171, -0.078]}
          rotation={[0.436, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015Badge_Geo_lodA.geometry}
        material={materials.Badge}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015Base_Geo_lodA.geometry}
        material={materials.Base}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015Carbon1M_Geo_lodA.geometry}
        material={materials.ExteriorPaint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015Coloured_Geo_lodA.geometry}
        material={materials.ExteriorPaint3}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015Engine_Geo_lodA.geometry}
        material={materials.Engine}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015Grille1_Geo_lodA.geometry}
        material={materials.Grille1}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015Grille2_Geo_lodA.geometry}
        material={materials.Grille2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015Grille3_Geo_lodA.geometry}
        material={materials.Grille3}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015Grille4_Geo_lodA.geometry}
        material={materials.Grille4}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015Interior_Geo_lodA.geometry}
        material={materials.Material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015Light_Geo_lodA.geometry}
        material={materials.Lights}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015ManufacturerPlate_Ge.geometry}
        material={materials.Plate}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015Paint_Geo_lodA.geometry}
        material={materials.BodyPaint}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015SeatBelt_Geo_lodA.geometry}
        material={materials.Seatbelt}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015Window_Geo_lodA.geometry}
        material={materials.Glass}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015_Wheel_1ACombine.geometry}
        material={materials.Wheel}
        position={[-0.81, 0.201, 1.264]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015CombinedCalliper.geometry}
          material={materials['BodyPaint.001']}
          position={[0, -0.158, 0.059]}
          rotation={[-Math.PI / 9, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015_Wheel_1ACombine001.geometry}
        material={materials.Wheel}
        position={[0.81, 0.201, 1.264]}
        rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015CombinedCalliper001.geometry}
          material={materials['BodyPaint.002']}
          position={[0, -0.158, 0.059]}
          rotation={[-Math.PI / 9, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015_Wheel_1ACombine002.geometry}
        material={materials.Wheel}
        position={[-0.81, 0.201, -1.44]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015CombinedCalliper002.geometry}
          material={materials['BodyPaint.003']}
          position={[0.002, 0.161, -0.062]}
          rotation={[2.793, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015Parking001.geometry}
          material={materials['ParkingBrake.001']}
          position={[0.009, -0.171, -0.078]}
          rotation={[0.436, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamborghini_AventadorLP7504Superveloce_2015RearLights.geometry}
        material={materials.RearLights}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('model/aventador_sv.glb')