/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { useEffect } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    MercedesAMG_GTR_2017_Wheel_1Combined3DWheel_3DWheel_front_L_Ins: THREE.Mesh
    MercedesAMG_GTRReward_2017CombinedCalliperBodyExotic6_Instance1: THREE.Mesh
    MercedesAMG_GTR_2017Badge_Geo_lodA: THREE.Mesh
    MercedesAMG_GTR_2017Base_Geo_lodA: THREE.Mesh
    MercedesAMG_GTR_2017Carbon1_Geo_lodA: THREE.Mesh
    MercedesAMG_GTR_2017Carbon2M_Geo_lodA: THREE.Mesh
    MercedesAMG_GTR_2017Coloured_Geo_lodA: THREE.Mesh
    MercedesAMG_GTR_2017Engine_Geo_lodA: THREE.Mesh
    MercedesAMG_GTR_2017Grille1_Geo_lodA: THREE.Mesh
    MercedesAMG_GTR_2017Grille2_Geo_lodA: THREE.Mesh
    MercedesAMG_GTR_2017Grille3_Geo_lodA: THREE.Mesh
    MercedesAMG_GTR_2017Grille4_Geo_lodA: THREE.Mesh
    MercedesAMG_GTR_2017Interior_Geo_lodA: THREE.Mesh
    MercedesAMG_GTR_2017Light_Geo_lodA: THREE.Mesh
    MercedesAMG_GTR_2017ManufacturerPlate_Geo_lodA: THREE.Mesh
    MercedesAMG_GTR_2017Paint_Geo_lodA: THREE.Mesh
    MercedesAMG_GTR_2017SeatBelt_Geo_lodA: THREE.Mesh
    MercedesAMG_GTR_2017Window_Geo_lodA: THREE.Mesh
    MercedesAMG_GTR_2017RearBadge: THREE.Mesh
    MercedesAMG_GTR_2017RearLights: THREE.Mesh
    MercedesAMG_GTR_2017FrontBadge: THREE.Mesh
    MercedesAMG_GTR_2017_Wheel_1Combined3DWheel_3DWheel_front_L: THREE.Mesh
    MercedesAMG_GTRReward_2017CombinedCalliperBodyExotic6_Insta: THREE.Mesh
    MercedesAMG_GTR_2017_Wheel_1Combined3DWheel_3DWheel_front_L001: THREE.Mesh
    MercedesAMG_GTRReward_2017CombinedCalliperBodyExotic6_Insta001: THREE.Mesh
    MercedesAMG_GTR_2017_Wheel_1Combined3DWheel_3DWheel_front_L002: THREE.Mesh
    MercedesAMG_GTRReward_2017CombinedCalliperBodyExotic6_Insta002: THREE.Mesh
    MercedesAMG_GTR_2017Roof: THREE.Mesh
    MercedesAMG_GTR_2017RearDiffuser: THREE.Mesh
  }
  materials: {
    Wheel: THREE.MeshPhysicalMaterial
    Caliper: THREE.MeshStandardMaterial
    Badge: THREE.MeshPhysicalMaterial
    Base: THREE.MeshStandardMaterial
    CarbonFiber: THREE.MeshPhysicalMaterial
    Paint2: THREE.MeshPhysicalMaterial
    Engine: THREE.MeshStandardMaterial
    Grille1: THREE.MeshStandardMaterial
    Grille2: THREE.MeshStandardMaterial
    Grille3: THREE.MeshStandardMaterial
    Grille4: THREE.MeshStandardMaterial
    Interior: THREE.MeshStandardMaterial
    Lights: THREE.MeshPhysicalMaterial
    Plate: THREE.MeshPhysicalMaterial
    Paint: THREE.MeshPhysicalMaterial
    Seatbelt: THREE.MeshStandardMaterial
    Glass: THREE.MeshPhysicalMaterial
    MetallicBadging: THREE.MeshPhysicalMaterial
    RearLights: THREE.MeshPhysicalMaterial
  }
}

export function AMGGTR(props: any) {
    const { nodes, materials } = useGLTF("models/amggtr.glb") as GLTFResult;
  
    useEffect(() => {
      // car paint
      Object.entries(materials).map((material) => {
        if (material[0] == "Paint") {
          material[1].color = new THREE.Color(props.color.hexCode);
        }
        material[1].needsUpdate = true;
      });
    }, [materials, props]);
  
    return (
      <group {...props} dispose={null} scale={4} position={[0, -1.81, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017_Wheel_1Combined3DWheel_3DWheel_front_L_Ins.geometry}
        material={materials.Wheel}
        position={[-0.83, 0.254, 1.346]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.85, -1, -1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MercedesAMG_GTRReward_2017CombinedCalliperBodyExotic6_Instance1.geometry}
          material={materials.Caliper}
          position={[0.007, -0.18, 0]}
          scale={[1.176, 1, 1]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017Badge_Geo_lodA.geometry}
        material={materials.Badge}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017Base_Geo_lodA.geometry}
        material={materials.Base}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017Carbon1_Geo_lodA.geometry}
        material={materials.CarbonFiber}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017Carbon2M_Geo_lodA.geometry}
        material={materials.CarbonFiber}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017Coloured_Geo_lodA.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017Engine_Geo_lodA.geometry}
        material={materials.Engine}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017Grille1_Geo_lodA.geometry}
        material={materials.Grille1}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017Grille2_Geo_lodA.geometry}
        material={materials.Grille2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017Grille3_Geo_lodA.geometry}
        material={materials.Grille3}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017Grille4_Geo_lodA.geometry}
        material={materials.Grille4}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017Interior_Geo_lodA.geometry}
        material={materials.Interior}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017Light_Geo_lodA.geometry}
        material={materials.Lights}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017ManufacturerPlate_Geo_lodA.geometry}
        material={materials.Plate}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017Paint_Geo_lodA.geometry}
        material={materials.Paint}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017SeatBelt_Geo_lodA.geometry}
        material={materials.Seatbelt}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017Window_Geo_lodA.geometry}
        material={materials.Glass}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017RearBadge.geometry}
        material={materials.MetallicBadging}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017RearLights.geometry}
        material={materials.RearLights}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017FrontBadge.geometry}
        material={materials.MetallicBadging}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017_Wheel_1Combined3DWheel_3DWheel_front_L.geometry}
        material={materials.Wheel}
        position={[-0.82, 0.254, -1.283]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MercedesAMG_GTRReward_2017CombinedCalliperBodyExotic6_Insta.geometry}
          material={materials.Caliper}
          position={[0.01, 0.18, 0]}
          rotation={[-Math.PI, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017_Wheel_1Combined3DWheel_3DWheel_front_L001.geometry}
        material={materials.Wheel}
        position={[0.82, 0.254, -1.283]}
        rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MercedesAMG_GTRReward_2017CombinedCalliperBodyExotic6_Insta001.geometry}
          material={materials.Caliper}
          position={[0.01, 0.18, 0]}
          rotation={[-Math.PI, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017_Wheel_1Combined3DWheel_3DWheel_front_L002.geometry}
        material={materials.Wheel}
        position={[0.83, 0.254, 1.346]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.85, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MercedesAMG_GTRReward_2017CombinedCalliperBodyExotic6_Insta002.geometry}
          material={materials.Caliper}
          position={[0.007, -0.18, 0]}
          scale={[1.176, 1, 1]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017Roof.geometry}
        material={materials.CarbonFiber}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesAMG_GTR_2017RearDiffuser.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('models/amggtr.glb')
