/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { useEffect } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    MercedesBenz_SLSAMGBlackSeries_2013_Wheel_1Combined3DWheel_3DWh: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013CombinedCalliperBodyExotic6_: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013Badge_Geo_lodA: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013Base_Geo_lodA: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013Carbon1_Geo_lodA: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013Carbon2_Geo_lodA: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013Coloured_Geo_lodA: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013Engine_Geo_lodA: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013Grille1_Geo_lodA: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013Grille2_Geo_lodA: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013Grille3_Geo_lodA: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013Interior_Geo_lodA: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013Light_Geo_lodA: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013ManufacturerPlate_Geo_lodA: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013Paint_Geo_lodA: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013SeatBelt_Geo_lodA: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013Window_Geo_lodA: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013RearLights: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013Coloured_Geo_lodA001: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013Coloured_Geo_lodA002: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013Coloured_Geo_lodA003: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013_Wheel_1Combined3DWheel_: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013CombinedCalliperBodyExot: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013_Wheel_1Combined3DWheel_001: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013CombinedCalliperBodyExot001: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013_Wheel_1Combined3DWheel_002: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013CombinedCalliperBodyExot002: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013_Wheel_1Combined3DWheel_003: THREE.Mesh
    MercedesBenz_SLSAMGBlackSeries_2013CombinedCalliperBodyExot003: THREE.Mesh
  }
  materials: {
    Wheel: THREE.MeshPhysicalMaterial
    Caliper: THREE.MeshStandardMaterial
    Badge: THREE.MeshPhysicalMaterial
    Paint2: THREE.MeshPhysicalMaterial
    CarbonFiber: THREE.MeshPhysicalMaterial
    Engine: THREE.MeshStandardMaterial
    Grille1: THREE.MeshStandardMaterial
    Grille2: THREE.MeshStandardMaterial
    Grille3: THREE.MeshStandardMaterial
    Interior: THREE.MeshStandardMaterial
    Lights: THREE.MeshStandardMaterial
    Plate: THREE.MeshPhysicalMaterial
    Paint: THREE.MeshPhysicalMaterial
    Glass: THREE.MeshPhysicalMaterial
    RearLights: THREE.MeshPhysicalMaterial
    MetallicBadging: THREE.MeshPhysicalMaterial
    ['Wheel.004']: THREE.MeshPhysicalMaterial
    ['Caliper.004']: THREE.MeshStandardMaterial
  }
}

export function SLSAMGBLK(props: any) {
  const { nodes, materials } = useGLTF('models/sls_amg_blk.glb') as GLTFResult

  useEffect(() => {
    // car paint
    Object.entries(materials).map((material) => {
      if (material[0] == "Paint") {
        material[1].color = new THREE.Color(props.color.hexCode);
      }
      material[1].needsUpdate = true;
    });
  }, [materials, props]);


  return (
    <group {...props} dispose={null} scale={4} position={[0, -1.69, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013_Wheel_1Combined3DWheel_3DWh.geometry}
        material={materials.Wheel}
        position={[0.821, 0.228, -1.307]}
        rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013CombinedCalliperBodyExotic6_.geometry}
          material={materials.Caliper}
          position={[0.008, 0.176, 0]}
          rotation={[-Math.PI, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013Badge_Geo_lodA.geometry}
        material={materials.Badge}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013Base_Geo_lodA.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013Carbon1_Geo_lodA.geometry}
        material={materials.CarbonFiber}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013Carbon2_Geo_lodA.geometry}
        material={materials.CarbonFiber}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013Coloured_Geo_lodA.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013Engine_Geo_lodA.geometry}
        material={materials.Engine}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013Grille1_Geo_lodA.geometry}
        material={materials.Grille1}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013Grille2_Geo_lodA.geometry}
        material={materials.Grille2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013Grille3_Geo_lodA.geometry}
        material={materials.Grille3}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013Interior_Geo_lodA.geometry}
        material={materials.Interior}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013Light_Geo_lodA.geometry}
        material={materials.Lights}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013ManufacturerPlate_Geo_lodA.geometry}
        material={materials.Plate}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013Paint_Geo_lodA.geometry}
        material={materials.Paint}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013SeatBelt_Geo_lodA.geometry}
        material={nodes.MercedesBenz_SLSAMGBlackSeries_2013SeatBelt_Geo_lodA.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013Window_Geo_lodA.geometry}
        material={materials.Glass}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013RearLights.geometry}
        material={materials.RearLights}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013Coloured_Geo_lodA001.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013Coloured_Geo_lodA002.geometry}
        material={materials.MetallicBadging}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013Coloured_Geo_lodA003.geometry}
        material={materials.MetallicBadging}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013_Wheel_1Combined3DWheel_.geometry}
        material={materials.Wheel}
        position={[0.842, 0.228, 1.367]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.85, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013CombinedCalliperBodyExot.geometry}
          material={materials.Caliper}
          position={[0.008, -0.176, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013_Wheel_1Combined3DWheel_001.geometry}
        material={materials.Wheel}
        position={[-0.821, 0.228, -1.307]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013CombinedCalliperBodyExot001.geometry}
          material={materials.Caliper}
          position={[0.008, 0.176, 0]}
          rotation={[-Math.PI, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013_Wheel_1Combined3DWheel_002.geometry}
        material={materials.Wheel}
        position={[0.821, 0.228, -1.307]}
        rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013CombinedCalliperBodyExot002.geometry}
          material={materials.Caliper}
          position={[0.008, 0.176, 0]}
          rotation={[-Math.PI, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013_Wheel_1Combined3DWheel_003.geometry}
        material={materials['Wheel.004']}
        position={[-0.842, 0.228, 1.367]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.85, -1, -1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MercedesBenz_SLSAMGBlackSeries_2013CombinedCalliperBodyExot003.geometry}
          material={materials['Caliper.004']}
          position={[0.008, -0.176, 0]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('models/sls_amg_blk.glb')