/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { useEffect } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Porsche_911GT3RS_2016_Wheel_1Combined3DWheel_3DWheel_front_L_In: THREE.Mesh
    Porsche_911GT3RSCrew_2016CombinedCalliperBodyExotic6_Instance1_: THREE.Mesh
    Porsche_911GT3RS_2016Badge_Geo_lodA: THREE.Mesh
    Porsche_911GT3RS_2016Base_Geo_lodA: THREE.Mesh
    Porsche_911GT3RS_2016Carbon1_Geo_lodA: THREE.Mesh
    Porsche_911GT3RS_2016Carbon2_Geo_lodA: THREE.Mesh
    Porsche_911GT3RS_2016Coloured_Geo_lodA: THREE.Mesh
    Porsche_911GT3RS_2016Grille1_Geo_lodA: THREE.Mesh
    Porsche_911GT3RS_2016Grille2_Geo_lodA: THREE.Mesh
    Porsche_911GT3RS_2016Grille3_Geo_lodA: THREE.Mesh
    Porsche_911GT3RS_2016Grille4_Geo_lodA: THREE.Mesh
    Porsche_911GT3RS_2016Interior_Geo_lodA: THREE.Mesh
    Porsche_911GT3RS_2016Light_Geo_lodA: THREE.Mesh
    Porsche_911GT3RS_2016ManufacturerPlate_Geo_lodA: THREE.Mesh
    Porsche_911GT3RS_2016Paint_Geo_lodA: THREE.Mesh
    Porsche_911GT3RS_2016SeatBelt_Geo_lodA: THREE.Mesh
    Porsche_911GT3RS_2016Window_Geo_lodA: THREE.Mesh
    Porsche_911GT3RS_2016RearLights: THREE.Mesh
    Porsche_911GT3RS_2016_Wheel_1Combined3DWheel_3DWheel_front_: THREE.Mesh
    Porsche_911GT3RSCrew_2016CombinedCalliperBodyExotic6_Instan: THREE.Mesh
    Porsche_911GT3RS_2016_Wheel_1Combined3DWheel_3DWheel_front_001: THREE.Mesh
    Porsche_911GT3RSCrew_2016CombinedCalliperBodyExotic6_Instan001: THREE.Mesh
    Porsche_911GT3RS_2016_Wheel_1Combined3DWheel_3DWheel_front_002: THREE.Mesh
    Porsche_911GT3RSCrew_2016CombinedCalliperBodyExotic6_Instan002: THREE.Mesh
  }
  materials: {
    Wheels: THREE.MeshPhysicalMaterial
    Caliper: THREE.MeshPhysicalMaterial
    Badge: THREE.MeshPhysicalMaterial
    Base: THREE.MeshStandardMaterial
    Carbon1: THREE.MeshStandardMaterial
    Paint2: THREE.MeshPhysicalMaterial
    Grille1: THREE.MeshStandardMaterial
    Grille2: THREE.MeshStandardMaterial
    Grille3: THREE.MeshStandardMaterial
    Grille4: THREE.MeshStandardMaterial
    Interior: THREE.MeshStandardMaterial
    Lights: THREE.MeshStandardMaterial
    Plate: THREE.MeshPhysicalMaterial
    Paint: THREE.MeshPhysicalMaterial
    Seatbelt: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    RearLights: THREE.MeshPhysicalMaterial
    ['Wheels.002']: THREE.MeshPhysicalMaterial
    ['Caliper.002']: THREE.MeshPhysicalMaterial
    ['Wheels.003']: THREE.MeshPhysicalMaterial
    ['Caliper.003']: THREE.MeshPhysicalMaterial
  }
}

export function Porsche911(props: any) {
  const { nodes, materials } = useGLTF('models/911gt3rs.glb') as GLTFResult

  useEffect(() => {
    // car paint
    Object.entries(materials).map((material) => {
      if (material[0] == "Paint") {
        material[1].color = new THREE.Color(props.color.hexCode);
      }
      material[1].needsUpdate = true;
    });
  }, [materials, props]);

  return (
    <group {...props} dispose={null} scale={4} position={[0, -2.23, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016_Wheel_1Combined3DWheel_3DWheel_front_L_In.geometry}
        material={materials.Wheels}
        position={[0.788, 0.368, 1.223]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.8, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Porsche_911GT3RSCrew_2016CombinedCalliperBodyExotic6_Instance1_.geometry}
          material={materials.Caliper}
          position={[0.008, -0.185, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016Badge_Geo_lodA.geometry}
        material={materials.Badge}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016Base_Geo_lodA.geometry}
        material={materials.Base}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016Carbon1_Geo_lodA.geometry}
        material={materials.Carbon1}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016Carbon2_Geo_lodA.geometry}
        material={materials.Carbon1}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016Coloured_Geo_lodA.geometry}
        material={materials.Paint2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016Grille1_Geo_lodA.geometry}
        material={materials.Grille1}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016Grille2_Geo_lodA.geometry}
        material={materials.Grille2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016Grille3_Geo_lodA.geometry}
        material={materials.Grille3}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016Grille4_Geo_lodA.geometry}
        material={materials.Grille4}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016Interior_Geo_lodA.geometry}
        material={materials.Interior}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016Light_Geo_lodA.geometry}
        material={materials.Lights}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016ManufacturerPlate_Geo_lodA.geometry}
        material={materials.Plate}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016Paint_Geo_lodA.geometry}
        material={materials.Paint}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016SeatBelt_Geo_lodA.geometry}
        material={materials.Seatbelt}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016Window_Geo_lodA.geometry}
        material={materials.Glass}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016RearLights.geometry}
        material={materials.RearLights}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016_Wheel_1Combined3DWheel_3DWheel_front_.geometry}
        material={materials.Wheels}
        position={[0.775, 0.368, -1.229]}
        rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Porsche_911GT3RSCrew_2016CombinedCalliperBodyExotic6_Instan.geometry}
          material={materials.Caliper}
          position={[0.011, 0.162, 0.06]}
          rotation={[-2.793, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016_Wheel_1Combined3DWheel_3DWheel_front_001.geometry}
        material={materials['Wheels.002']}
        position={[-0.775, 0.368, -1.229]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Porsche_911GT3RSCrew_2016CombinedCalliperBodyExotic6_Instan001.geometry}
          material={materials['Caliper.002']}
          position={[0.011, 0.162, 0.06]}
          rotation={[-2.793, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Porsche_911GT3RS_2016_Wheel_1Combined3DWheel_3DWheel_front_002.geometry}
        material={materials['Wheels.003']}
        position={[-0.788, 0.368, 1.223]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.8, -1, -1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Porsche_911GT3RSCrew_2016CombinedCalliperBodyExotic6_Instan002.geometry}
          material={materials['Caliper.003']}
          position={[0.008, -0.185, 0]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('models/911gt3rs.glb')
