/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_145: THREE.Mesh
    Object_150: THREE.Mesh
    Object_148: THREE.Mesh
    Object_156: THREE.Mesh
    Object_154: THREE.Mesh
    Object_152: THREE.Mesh
    Object_142: THREE.Mesh
    Object_133: THREE.Mesh
    Object_131: THREE.Mesh
    Object_139: THREE.Mesh
    Object_137: THREE.Mesh
    Object_135: THREE.Mesh
    Object_119: THREE.Mesh
    Object_123: THREE.Mesh
    Object_121: THREE.Mesh
    Object_128: THREE.Mesh
    Object_126: THREE.Mesh
    Object_239: THREE.Mesh
    Object_242: THREE.Mesh
    Object_219: THREE.Mesh
    Object_215: THREE.Mesh
    Object_213: THREE.Mesh
    Object_229: THREE.Mesh
    Object_225: THREE.Mesh
    Object_233: THREE.Mesh
    Object_227: THREE.Mesh
    Object_231: THREE.Mesh
    Object_223: THREE.Mesh
    Object_221: THREE.Mesh
    Object_217: THREE.Mesh
    Object_236: THREE.Mesh
    Object_277: THREE.Mesh
    Object_69: THREE.Mesh
    Object_67: THREE.Mesh
    Object_71: THREE.Mesh
    Object_84: THREE.Mesh
    Object_74: THREE.Mesh
    Object_81: THREE.Mesh
    Object_77: THREE.Mesh
    Object_79: THREE.Mesh
    Object_29: THREE.Mesh
    Object_53: THREE.Mesh
    Object_35: THREE.Mesh
    Object_32: THREE.Mesh
    Object_38: THREE.Mesh
    Object_56: THREE.Mesh
    Object_50: THREE.Mesh
    Object_44: THREE.Mesh
    Object_47: THREE.Mesh
    Object_41: THREE.Mesh
    Object_109: THREE.Mesh
    Object_107: THREE.Mesh
    Object_111: THREE.Mesh
    Object_104: THREE.Mesh
    Object_116: THREE.Mesh
    Object_114: THREE.Mesh
    Object_87: THREE.Mesh
    Object_99: THREE.Mesh
    Object_95: THREE.Mesh
    Object_93: THREE.Mesh
    Object_89: THREE.Mesh
    Object_97: THREE.Mesh
    Object_91: THREE.Mesh
    Object_101: THREE.Mesh
    Object_10: THREE.Mesh
    Object_8: THREE.Mesh
    Object_16: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_14: THREE.Mesh
    Object_20: THREE.Mesh
    Object_26: THREE.Mesh
    Object_18: THREE.Mesh
    Object_12: THREE.Mesh
    Object_62: THREE.Mesh
    Object_64: THREE.Mesh
    Object_59: THREE.Mesh
    Object_280: THREE.Mesh
    Object_172: THREE.Mesh
    Object_170: THREE.Mesh
    Object_178: THREE.Mesh
    Object_176: THREE.Mesh
    Object_174: THREE.Mesh
    Object_283: THREE.Mesh
    Object_161: THREE.Mesh
    Object_159: THREE.Mesh
    Object_167: THREE.Mesh
    Object_165: THREE.Mesh
    Object_163: THREE.Mesh
    Object_204: THREE.Mesh
    Object_207: THREE.Mesh
    Object_187: THREE.Mesh
    Object_183: THREE.Mesh
    Object_181: THREE.Mesh
    Object_197: THREE.Mesh
    Object_193: THREE.Mesh
    Object_201: THREE.Mesh
    Object_195: THREE.Mesh
    Object_199: THREE.Mesh
    Object_191: THREE.Mesh
    Object_189: THREE.Mesh
    Object_185: THREE.Mesh
    Object_210: THREE.Mesh
    Object_274: THREE.Mesh
    Object_271: THREE.Mesh
    Object_268: THREE.Mesh
    Object_266: THREE.Mesh
    Object_259: THREE.Mesh
    Object_261: THREE.Mesh
    Object_263: THREE.Mesh
    Object_247: THREE.Mesh
    Object_245: THREE.Mesh
    Object_249: THREE.Mesh
    Object_256: THREE.Mesh
    Object_252: THREE.Mesh
    Object_254: THREE.Mesh
  }
  materials: {
    Misc_2: THREE.MeshStandardMaterial
    Brake_Disc: THREE.MeshStandardMaterial
    Painted_Black: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Tire_Sidewall: THREE.MeshStandardMaterial
    Tire_Treads: THREE.MeshStandardMaterial
    Body_Color: THREE.MeshPhysicalMaterial
    Bolt_2_Interior: THREE.MeshStandardMaterial
    Plastic: THREE.MeshStandardMaterial
    Other_Glasses_than_Windshield: THREE.MeshStandardMaterial
    Windshield: THREE.MeshStandardMaterial
    Interior: THREE.MeshStandardMaterial
    Aluminium: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Engine_Decals: THREE.MeshStandardMaterial
    Grill_4_Speakers: THREE.MeshStandardMaterial
    Interior_Buttons: THREE.MeshStandardMaterial
    Interior_Trim_2: THREE.MeshStandardMaterial
    Mirror: THREE.MeshStandardMaterial
    Left_Indicator: THREE.MeshStandardMaterial
    Chrome_Engine_Pipes_Use_Grill_5_as_BW_to_Bump_to_Normal: THREE.MeshStandardMaterial
    Engine_Cover: THREE.MeshStandardMaterial
    Carbon_Fiber: THREE.MeshPhysicalMaterial
    Grille_1: THREE.MeshStandardMaterial
    Grille_3: THREE.MeshStandardMaterial
    Badges: THREE.MeshStandardMaterial
    Brake_Lights: THREE.MeshStandardMaterial
    Day_Lights: THREE.MeshStandardMaterial
    Lights: THREE.MeshStandardMaterial
    Headlights: THREE.MeshStandardMaterial
    License_Plate_Lights: THREE.MeshStandardMaterial
    Reverse_Lights: THREE.MeshStandardMaterial
    Taillights: THREE.MeshStandardMaterial
    Right_Indicator: THREE.MeshStandardMaterial
    Gauges: THREE.MeshStandardMaterial
    Interior_Display: THREE.MeshStandardMaterial
    Interior_Trim: THREE.MeshStandardMaterial
    Carpet: THREE.MeshStandardMaterial
    Interior_Aluminium: THREE.MeshStandardMaterial
    Seats_Adjust_the_leather_texture_using_Color_Ramp_or_using_HSV: THREE.MeshStandardMaterial
    Chrome: THREE.MeshStandardMaterial
    Grille_6: THREE.MeshStandardMaterial
    Grille_7: THREE.MeshStandardMaterial
    Invisible_Unimportant_Black: THREE.MeshStandardMaterial
    Misc: THREE.MeshStandardMaterial
    ['Mat_supergt.209']: THREE.MeshStandardMaterial
    Interior_Badge: THREE.MeshStandardMaterial
    Dark_Engine_View_Glass: THREE.MeshStandardMaterial
  }
}

export function C8(props: any) {
  const { nodes, materials } = useGLTF('model/c8.glb') as GLTFResult

  useEffect(() => {
    // car paint
    Object.entries(materials).map((material) => {
      if (material[0] == "Body_Color") {
        material[1].color = new THREE.Color(props.color.hexCode);
      }
      material[1].needsUpdate = true;
    });
  }, [materials, props]);

  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 2, 0]} position={[0, -1.71, 0]}>
        <group scale={0.03}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_145.geometry}
            material={materials.Misc_2}
            position={[-93.3, 37.5, -144.7]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <group
            position={[-93.3, 37.4, -144.8]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_150.geometry}
              material={materials.Brake_Disc}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_148.geometry}
              material={materials.Painted_Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_156.geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_154.geometry}
              material={materials.Tire_Sidewall}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_152.geometry}
              material={materials.Tire_Treads}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_142.geometry}
            material={materials.Misc_2}
            position={[93.3, 37.4, -144.8]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <group position={[93.3, 37.4, -144.8]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_133.geometry}
              material={materials.Brake_Disc}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_131.geometry}
              material={materials.Painted_Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_139.geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_137.geometry}
              material={materials.Tire_Sidewall}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_135.geometry}
              material={materials.Tire_Treads}
            />
          </group>
          <group position={[-0.005, 89.108, -117.937]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_119.geometry}
              material={materials.Body_Color}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_123.geometry}
              material={materials.Bolt_2_Interior}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_121.geometry}
              material={materials.Plastic}
            />
          </group>
          <group position={[0, 107.664, -32.526]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_128.geometry}
              material={materials.Other_Glasses_than_Windshield}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_126.geometry}
              material={materials.Windshield}
            />
          </group>
          <group position={[-96.2, 60.6, -86.5]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_239.geometry}
              material={materials.Other_Glasses_than_Windshield}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_242.geometry}
              material={materials.Interior}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_219.geometry}
              material={materials.Aluminium}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_215.geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_213.geometry}
              material={materials.Body_Color}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_229.geometry}
              material={materials.Engine_Decals}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_225.geometry}
              material={materials.Grill_4_Speakers}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_233.geometry}
              material={materials.Interior_Buttons}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_227.geometry}
              material={materials.Interior_Trim_2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_231.geometry}
              material={materials.Interior}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_223.geometry}
              material={materials.Mirror}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_221.geometry}
              material={materials.Painted_Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_217.geometry}
              material={materials.Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_236.geometry}
              material={materials.Left_Indicator}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_277.geometry}
            material={materials.Black}
            position={[-72.85, 81.173, -125.058]}
            rotation={[-0.562, 0, 0]}
            scale={100}
          />
          <group position={[0, 71, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_69.geometry}
              material={materials.Chrome_Engine_Pipes_Use_Grill_5_as_BW_to_Bump_to_Normal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_67.geometry}
              material={materials.Engine_Cover}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_71.geometry}
              material={materials.Engine_Decals}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_84.geometry}
              material={materials.Carbon_Fiber}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_74.geometry}
              material={materials.Engine_Decals}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_81.geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_77.geometry}
              material={materials.Grille_1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_79.geometry}
              material={materials.Grille_3}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_29.geometry}
              material={materials.Badges}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_53.geometry}
              material={materials.Brake_Lights}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_35.geometry}
              material={materials.Day_Lights}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_32.geometry}
              material={materials.Lights}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_38.geometry}
              material={materials.Headlights}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_56.geometry}
              material={materials.License_Plate_Lights}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_50.geometry}
              material={materials.Reverse_Lights}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_44.geometry}
              material={materials.Left_Indicator}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_47.geometry}
              material={materials.Taillights}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_41.geometry}
              material={materials.Right_Indicator}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_109.geometry}
              material={materials.Gauges}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_107.geometry}
              material={materials.Interior_Buttons}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_111.geometry}
              material={materials.Interior_Display}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_104.geometry}
              material={materials.Interior}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_116.geometry}
              material={materials.Badges}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_114.geometry}
              material={materials.Interior_Trim}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_87.geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_99.geometry}
              material={materials.Carpet}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_95.geometry}
              material={materials.Engine_Decals}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_93.geometry}
              material={materials.Grill_4_Speakers}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_89.geometry}
              material={materials.Interior_Aluminium}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_97.geometry}
              material={materials.Interior}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_91.geometry}
              material={materials.Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_101.geometry}
              material={materials.Seats_Adjust_the_leather_texture_using_Color_Ramp_or_using_HSV}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials.Body_Color}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_16.geometry}
              material={materials.Chrome}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_22.geometry}
              material={materials.Grille_6}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_24.geometry}
              material={materials.Grille_7}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_14.geometry}
              material={materials.Invisible_Unimportant_Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_20.geometry}
              material={materials.Mirror}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_26.geometry}
              material={materials.Misc}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_18.geometry}
              material={materials.Painted_Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_12.geometry}
              material={materials.Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_62.geometry}
              material={materials.Body_Color}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_64.geometry}
              material={materials.Interior}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_59.geometry}
              material={materials.Misc}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_280.geometry}
            material={materials.Misc}
            position={[-93, 39.144, 163.221]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <group
            position={[-93, 39.139, 163.216]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={[100, 105, 105]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_172.geometry}
              material={materials.Brake_Disc}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_170.geometry}
              material={materials.Painted_Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_178.geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_176.geometry}
              material={materials.Tire_Sidewall}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_174.geometry}
              material={materials.Tire_Treads}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_283.geometry}
            material={materials.Misc}
            position={[93, 39.244, 163.321]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <group
            position={[93, 39.248, 163.326]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 105, 105]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_161.geometry}
              material={materials.Brake_Disc}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_159.geometry}
              material={materials.Painted_Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_167.geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_165.geometry}
              material={materials.Tire_Sidewall}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_163.geometry}
              material={materials.Tire_Treads}
            />
          </group>
          <group position={[96.277, 60.504, -86.518]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_204.geometry}
              material={materials.Other_Glasses_than_Windshield}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_207.geometry}
              material={materials.Interior}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_187.geometry}
              material={materials.Aluminium}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_183.geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_181.geometry}
              material={materials.Body_Color}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_197.geometry}
              material={materials.Engine_Decals}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_193.geometry}
              material={materials.Grill_4_Speakers}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_201.geometry}
              material={materials.Interior_Buttons}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_195.geometry}
              material={materials.Interior_Trim_2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_199.geometry}
              material={materials.Interior}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_191.geometry}
              material={materials.Mirror}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_189.geometry}
              material={materials.Painted_Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_185.geometry}
              material={materials.Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_210.geometry}
              material={materials.Right_Indicator}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_274.geometry}
            material={materials.Black}
            position={[-14.407, 83.51, -142.909]}
            rotation={[-0.544, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_271.geometry}
            material={materials['Mat_supergt.209']}
            position={[-40.143, 85.455, -68.471]}
            rotation={[-1.712, 0, 0]}
            scale={100}
          />
          <group position={[-40.165, 76.978, -46.396]} rotation={[-1.824, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_268.geometry}
              material={materials.Interior_Badge}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_266.geometry}
              material={materials.Interior}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_259.geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_261.geometry}
              material={materials.Interior_Aluminium}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_263.geometry}
              material={materials.Interior}
            />
          </group>
          <group position={[0, 126.598, 69.859]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_247.geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_245.geometry}
              material={materials.Body_Color}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_249.geometry}
              material={materials.Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_256.geometry}
              material={materials.Badges}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_252.geometry}
              material={materials.Dark_Engine_View_Glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_254.geometry}
              material={materials.Grille_7}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('model/c8.glb')
