/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AleixoAlonso (https://sketchfab.com/AleixoAlonso)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-studio-light-771d351d2329444fab348909ebfd160b
Title: Simple Studio Light
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['#LMP0001_Bottom_#LMP0001_Textures_0']: THREE.Mesh
    ['#LMP0001_Middle_#LMP0001_Textures_0']: THREE.Mesh
    ['#LMP0001_Top_#LMP0001_Textures_0']: THREE.Mesh
    ['Stand001_#LMP0001_Textures_0']: THREE.Mesh
    ['#LMP0001_Lightbox_#LMP0001_Textures_0']: THREE.Mesh
  }
  materials: {
    LMP0001_Textures: THREE.MeshStandardMaterial
  }
}

export function SpotlightProp(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('models/spotlight.glb') as GLTFResult
  return (
    <group {...props} dispose={null} scale={1.5} position={props.position} rotation={props.rotation}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={2.514}>
          <mesh
            geometry={nodes['#LMP0001_Bottom_#LMP0001_Textures_0'].geometry}
            material={materials.LMP0001_Textures}
          />
          <mesh
            geometry={nodes['#LMP0001_Middle_#LMP0001_Textures_0'].geometry}
            material={materials.LMP0001_Textures}
          />
          <mesh
            geometry={nodes['#LMP0001_Top_#LMP0001_Textures_0'].geometry}
            material={materials.LMP0001_Textures}
          />
          <group position={[0, 0, 1.664]}>
            <mesh
              geometry={nodes['Stand001_#LMP0001_Textures_0'].geometry}
              material={materials.LMP0001_Textures}
            />
            <group position={[0, 0.001, 0.048]}>
              <mesh
                geometry={nodes['#LMP0001_Lightbox_#LMP0001_Textures_0'].geometry}
                material={materials.LMP0001_Textures}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/spotlight.glb')
